export class LogicLiveEvent {
    static COUNT = 41

    static encode(stream) { 
        // LogicLiveEvent #1
        stream.writeVInt(7096)
        stream.writeStringReference('Offer - Become The World Champion! - glory-4 (Glory B)')
        stream.writeVInt(0)
        stream.writeVInt(1786493700)
        stream.writeVInt(1786665540)
        stream.writeVInt(1786493700)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Offer - Become The World Champion! - glory-4 (Glory B)')
        stream.writeString('{"Color":"#448932","ShopSpenderDaysInActive":7,"ShopSpenderPercentageIncrease":50,"ShopSpenderCapWeekly":true,"ShopSpenderCapMonthly":true,"ShopSpenderCapAllTime":true,"OverrideName":"chronos-special-offer-glory-4","TierDefaultShopItem":"7011005","Tier1ShopItem":"7011005","Tier2ShopItem":"7011005","Tier3ShopItem":"7011005","Tier4ShopItem":"7011005","Tier5ShopItem":"7011005","Tier6ShopItem":"7011005","Tier7ShopItem":"7011007","Tier8ShopItem":"7011007","Tier9ShopItem":"7011007","Tier10ShopItem":"7011010","Tier15ShopItem":"7011015","Tier20ShopItem":"7011020","Tier50ShopItem":"7011050","Tier60ShopItem":"7011060","lookupValues":[]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        // LogicLiveEvent #2
        stream.writeVInt(7099)
        stream.writeStringReference('Offer - Celebrating your Best Goals! - football-12 (Champions Chest)')
        stream.writeVInt(0)
        stream.writeVInt(1786666500)
        stream.writeVInt(1786838340)
        stream.writeVInt(1786666500)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Offer - Celebrating your Best Goals! - football-12 (Champions Chest)')
        stream.writeString('{"Color":"#448932","ShopSpenderDaysInActive":7,"ShopSpenderPercentageIncrease":50,"ShopSpenderCapWeekly":true,"ShopSpenderCapMonthly":true,"ShopSpenderCapAllTime":true,"OverrideName":"chronos-special-offer-football-12","TierDefaultShopItem":"7013010","Tier1ShopItem":"7013002","Tier2ShopItem":"7013002","Tier3ShopItem":"7013003","Tier4ShopItem":"7013005","Tier5ShopItem":"7013005","Tier6ShopItem":"7013007","Tier7ShopItem":"7013007","Tier8ShopItem":"7013010","Tier9ShopItem":"7013010","Tier10ShopItem":"7013010","Tier15ShopItem":"7013015","Tier20ShopItem":"7013020","Tier50ShopItem":"7013050","Tier60ShopItem":"7013060","lookupValues":[]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        // LogicLiveEvent #3
        stream.writeVInt(7118)
        stream.writeStringReference('2v2 - Melon Mayhem - 16W - Greenfield - MiniChest')
        stream.writeVInt(2)
        stream.writeVInt(1786622400)
        stream.writeVInt(1786707900)
        stream.writeVInt(1786536000)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('2v2 - Melon Mayhem - 16W - Greenfield - MiniChest')
        stream.writeString('{"Color":"#ae2d13","2V2Lookup":"264","lookupValues":[{"id":264,"name":"2v2 - Melon Mayhem - 16W - Greenfield - MiniChest","lookup":"2v2_event_lookup","parameters":{"NameKey":"survival-melon-mayhem-name","DescriptionKey":"survival-generic1-desc","GameModeConfig":{"GoaliesDisabled":true,"BallDensity":100,"BallScale":100,"NumberOfBallsOnOvertime":4,"DisableDeckRandomization":true,"ManaGeneration":100,"Arena":1,"NumberOfBalls":3},"BallType":"1","Deck":["43","43","43","43"],"IntermediateRewards":["4","59","5","60","65","7","189","74"],"WinsRequired":[2,4,6,8,10,12,14,16]}},{"id":1,"name":"Ball: Normal","lookup":"ball_lookup","parameters":{"Type":"ball"}},{"id":43,"name":"Spell: Melon","lookup":"spell_lookup","parameters":{"RefId":"melon"}},{"id":43,"name":"Spell: Melon","lookup":"spell_lookup","parameters":{"RefId":"melon"}},{"id":43,"name":"Spell: Melon","lookup":"spell_lookup","parameters":{"RefId":"melon"}},{"id":43,"name":"Spell: Melon","lookup":"spell_lookup","parameters":{"RefId":"melon"}},{"id":4,"name":"Reward: Gold (x25)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":25}},{"id":59,"name":"Reward: Spell - Random Core (x5)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"0","Amount":5}},{"id":5,"name":"Reward: Gold (x75)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":75}},{"id":60,"name":"Reward: Spell - Random Core (x10)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"0","Amount":10}},{"id":65,"name":"Reward: Spell - Random Pro (x3)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"1","Amount":3}},{"id":7,"name":"Reward: Gold (x150)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":150}},{"id":189,"name":"Reward: Chest - Silver Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"3","Amount":0}},{"id":74,"name":"Reward: Chest - Mini Event Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"16","Amount":0}}]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        // LogicLiveEvent #4
        stream.writeVInt(7119)
        stream.writeStringReference('2v2 - Melon Mayhem - 16W - Greenfield - MiniChest')
        stream.writeVInt(2)
        stream.writeVInt(1787227200)
        stream.writeVInt(1787312700)
        stream.writeVInt(1787140800)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('2v2 - Melon Mayhem - 16W - Greenfield - MiniChest')
        stream.writeString('{"Color":"#ae2d13","2V2Lookup":"264","lookupValues":[{"id":264,"name":"2v2 - Melon Mayhem - 16W - Greenfield - MiniChest","lookup":"2v2_event_lookup","parameters":{"NameKey":"survival-melon-mayhem-name","DescriptionKey":"survival-generic1-desc","GameModeConfig":{"GoaliesDisabled":true,"BallDensity":100,"BallScale":100,"NumberOfBallsOnOvertime":4,"DisableDeckRandomization":true,"ManaGeneration":100,"Arena":1,"NumberOfBalls":3},"BallType":"1","Deck":["43","43","43","43"],"IntermediateRewards":["4","59","5","60","65","7","189","74"],"WinsRequired":[2,4,6,8,10,12,14,16]}},{"id":1,"name":"Ball: Normal","lookup":"ball_lookup","parameters":{"Type":"ball"}},{"id":43,"name":"Spell: Melon","lookup":"spell_lookup","parameters":{"RefId":"melon"}},{"id":43,"name":"Spell: Melon","lookup":"spell_lookup","parameters":{"RefId":"melon"}},{"id":43,"name":"Spell: Melon","lookup":"spell_lookup","parameters":{"RefId":"melon"}},{"id":43,"name":"Spell: Melon","lookup":"spell_lookup","parameters":{"RefId":"melon"}},{"id":4,"name":"Reward: Gold (x25)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":25}},{"id":59,"name":"Reward: Spell - Random Core (x5)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"0","Amount":5}},{"id":5,"name":"Reward: Gold (x75)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":75}},{"id":60,"name":"Reward: Spell - Random Core (x10)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"0","Amount":10}},{"id":65,"name":"Reward: Spell - Random Pro (x3)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"1","Amount":3}},{"id":7,"name":"Reward: Gold (x150)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":150}},{"id":189,"name":"Reward: Chest - Silver Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"3","Amount":0}},{"id":74,"name":"Reward: Chest - Mini Event Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"16","Amount":0}}]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        // LogicLiveEvent #5
        stream.writeVInt(7122)
        stream.writeStringReference('2v2 - Triple Energy Rush - 20W - El Dorado - Event Chest')
        stream.writeVInt(2)
        stream.writeVInt(1786881600)
        stream.writeVInt(1786967100)
        stream.writeVInt(1786795200)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('2v2 - Triple Energy Rush - 20W - El Dorado - Event Chest')
        stream.writeString('{"Color":"#ae2d13","2V2Lookup":"293","lookupValues":[{"id":293,"name":"2v2 - Triple Energy Rush - 20W - El Dorado - Event Chest","lookup":"2v2_event_lookup","parameters":{"NameKey":"survival-triple-energy-rush-name","DescriptionKey":"survival-triple-energy-rush-desc","GameModeConfig":{"GoaliesDisabled":false,"BallDensity":100,"BallScale":100,"NumberOfBallsOnOvertime":2,"DisableDeckRandomization":false,"ManaGeneration":300,"Arena":4,"NumberOfBalls":1},"BallType":"1","IntermediateRewards":["59","6","189","236","189","173","237","11","190","214"],"WinsRequired":[2,4,6,8,10,12,14,16,18,20]}},{"id":1,"name":"Ball: Normal","lookup":"ball_lookup","parameters":{"Type":"ball"}},{"id":59,"name":"Reward: Spell - Random Core (x5)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"0","Amount":5}},{"id":6,"name":"Reward: Gold (x100)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":100}},{"id":189,"name":"Reward: Chest - Silver Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"3","Amount":0}},{"id":236,"name":"Reward: Spell - Random Pro (x4)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"1","Amount":4}},{"id":189,"name":"Reward: Chest - Silver Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"3","Amount":0}},{"id":173,"name":"Reward: Gold (x300)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":300}},{"id":237,"name":"Reward: Spell - Random Core (x40)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"0","Amount":40}},{"id":11,"name":"Reward: Gold (x500)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":500}},{"id":190,"name":"Reward: Chest - Golden Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"4","Amount":0}},{"id":214,"name":"Reward: Chest - Event Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"39","Amount":0}}]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        // LogicLiveEvent #6
        stream.writeVInt(7123)
        stream.writeStringReference('2v2 - Triple Energy Rush - 20W - El Dorado - Event Chest')
        stream.writeVInt(2)
        stream.writeVInt(1787486400)
        stream.writeVInt(1787571900)
        stream.writeVInt(1787400000)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('2v2 - Triple Energy Rush - 20W - El Dorado - Event Chest')
        stream.writeString('{"Color":"#ae2d13","2V2Lookup":"293","lookupValues":[{"id":293,"name":"2v2 - Triple Energy Rush - 20W - El Dorado - Event Chest","lookup":"2v2_event_lookup","parameters":{"NameKey":"survival-triple-energy-rush-name","DescriptionKey":"survival-triple-energy-rush-desc","GameModeConfig":{"GoaliesDisabled":false,"BallDensity":100,"BallScale":100,"NumberOfBallsOnOvertime":2,"DisableDeckRandomization":false,"ManaGeneration":300,"Arena":4,"NumberOfBalls":1},"BallType":"1","IntermediateRewards":["59","6","189","236","189","173","237","11","190","214"],"WinsRequired":[2,4,6,8,10,12,14,16,18,20]}},{"id":1,"name":"Ball: Normal","lookup":"ball_lookup","parameters":{"Type":"ball"}},{"id":59,"name":"Reward: Spell - Random Core (x5)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"0","Amount":5}},{"id":6,"name":"Reward: Gold (x100)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":100}},{"id":189,"name":"Reward: Chest - Silver Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"3","Amount":0}},{"id":236,"name":"Reward: Spell - Random Pro (x4)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"1","Amount":4}},{"id":189,"name":"Reward: Chest - Silver Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"3","Amount":0}},{"id":173,"name":"Reward: Gold (x300)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":300}},{"id":237,"name":"Reward: Spell - Random Core (x40)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"0","Amount":40}},{"id":11,"name":"Reward: Gold (x500)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":500}},{"id":190,"name":"Reward: Chest - Golden Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"4","Amount":0}},{"id":214,"name":"Reward: Chest - Event Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"39","Amount":0}}]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        // LogicLiveEvent #7
        stream.writeVInt(7126)
        stream.writeStringReference('2v2 - Explosive Madness - 20W - Greenfield - EventChest')
        stream.writeVInt(2)
        stream.writeVInt(1787054400)
        stream.writeVInt(1787139900)
        stream.writeVInt(1786968000)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('2v2 - Explosive Madness - 20W - Greenfield - EventChest')
        stream.writeString('{"Color":"#ae2d13","2V2Lookup":"255","lookupValues":[{"id":255,"name":"2v2 - Explosive Madness - 20W - Greenfield - EventChest","lookup":"2v2_event_lookup","parameters":{"NameKey":"survival-explosion-mayhem-name","DescriptionKey":"survival-explosion-mayhem-desc","GameModeConfig":{"GoaliesDisabled":true,"BallDensity":100,"BallScale":100,"NumberOfBallsOnOvertime":4,"DisableDeckRandomization":true,"ManaGeneration":200,"Arena":1,"NumberOfBalls":3},"BallType":"1","Deck":["45","45","45","45"],"WinsRequired":[2,4,6,8,10,12,14,16,18,20],"IntermediateRewards":["59","6","189","236","189","173","237","11","190","214"]}},{"id":1,"name":"Ball: Normal","lookup":"ball_lookup","parameters":{"Type":"ball"}},{"id":45,"name":"Spell: Mr. Fire","lookup":"spell_lookup","parameters":{"RefId":"explosive"}},{"id":45,"name":"Spell: Mr. Fire","lookup":"spell_lookup","parameters":{"RefId":"explosive"}},{"id":45,"name":"Spell: Mr. Fire","lookup":"spell_lookup","parameters":{"RefId":"explosive"}},{"id":45,"name":"Spell: Mr. Fire","lookup":"spell_lookup","parameters":{"RefId":"explosive"}},{"id":59,"name":"Reward: Spell - Random Core (x5)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"0","Amount":5}},{"id":6,"name":"Reward: Gold (x100)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":100}},{"id":189,"name":"Reward: Chest - Silver Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"3","Amount":0}},{"id":236,"name":"Reward: Spell - Random Pro (x4)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"1","Amount":4}},{"id":189,"name":"Reward: Chest - Silver Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"3","Amount":0}},{"id":173,"name":"Reward: Gold (x300)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":300}},{"id":237,"name":"Reward: Spell - Random Core (x40)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"0","Amount":40}},{"id":11,"name":"Reward: Gold (x500)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":500}},{"id":190,"name":"Reward: Chest - Golden Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"4","Amount":0}},{"id":214,"name":"Reward: Chest - Event Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"39","Amount":0}}]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        // LogicLiveEvent #8
        stream.writeVInt(7127)
        stream.writeStringReference('2v2 - Explosive Madness - 20W - Greenfield - EventChest')
        stream.writeVInt(2)
        stream.writeVInt(1787659200)
        stream.writeVInt(1787744700)
        stream.writeVInt(1787572800)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('2v2 - Explosive Madness - 20W - Greenfield - EventChest')
        stream.writeString('{"Color":"#ae2d13","2V2Lookup":"255","lookupValues":[{"id":255,"name":"2v2 - Explosive Madness - 20W - Greenfield - EventChest","lookup":"2v2_event_lookup","parameters":{"NameKey":"survival-explosion-mayhem-name","DescriptionKey":"survival-explosion-mayhem-desc","GameModeConfig":{"GoaliesDisabled":true,"BallDensity":100,"BallScale":100,"NumberOfBallsOnOvertime":4,"DisableDeckRandomization":true,"ManaGeneration":200,"Arena":1,"NumberOfBalls":3},"BallType":"1","Deck":["45","45","45","45"],"WinsRequired":[2,4,6,8,10,12,14,16,18,20],"IntermediateRewards":["59","6","189","236","189","173","237","11","190","214"]}},{"id":1,"name":"Ball: Normal","lookup":"ball_lookup","parameters":{"Type":"ball"}},{"id":45,"name":"Spell: Mr. Fire","lookup":"spell_lookup","parameters":{"RefId":"explosive"}},{"id":45,"name":"Spell: Mr. Fire","lookup":"spell_lookup","parameters":{"RefId":"explosive"}},{"id":45,"name":"Spell: Mr. Fire","lookup":"spell_lookup","parameters":{"RefId":"explosive"}},{"id":45,"name":"Spell: Mr. Fire","lookup":"spell_lookup","parameters":{"RefId":"explosive"}},{"id":59,"name":"Reward: Spell - Random Core (x5)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"0","Amount":5}},{"id":6,"name":"Reward: Gold (x100)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":100}},{"id":189,"name":"Reward: Chest - Silver Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"3","Amount":0}},{"id":236,"name":"Reward: Spell - Random Pro (x4)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"1","Amount":4}},{"id":189,"name":"Reward: Chest - Silver Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"3","Amount":0}},{"id":173,"name":"Reward: Gold (x300)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":300}},{"id":237,"name":"Reward: Spell - Random Core (x40)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"0","Amount":40}},{"id":11,"name":"Reward: Gold (x500)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":500}},{"id":190,"name":"Reward: Chest - Golden Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"4","Amount":0}},{"id":214,"name":"Reward: Chest - Event Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"39","Amount":0}}]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        // LogicLiveEvent #9
        stream.writeVInt(7129)
        stream.writeStringReference('2v2 - No Goalie - 20W - ZenPalace - EpicChest')
        stream.writeVInt(2)
        stream.writeVInt(1787313600)
        stream.writeVInt(1787485500)
        stream.writeVInt(1787227200)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('2v2 - No Goalie - 20W - ZenPalace - EpicChest')
        stream.writeString('{"Color":"#ae2d13","2V2Lookup":"258","lookupValues":[{"id":258,"name":"2v2 - No Goalie - 20W - ZenPalace - EpicChest","lookup":"2v2_event_lookup","parameters":{"NameKey":"survival-no-goalie-name","DescriptionKey":"survival-no-goalie-desc","GameModeConfig":{"GoaliesDisabled":true,"BallDensity":100,"BallScale":100,"NumberOfBallsOnOvertime":2,"DisableDeckRandomization":false,"ManaGeneration":100,"Arena":7,"NumberOfBalls":1},"BallType":"1","IntermediateRewards":["236","189","173","237","190","238","228","190","150","76"],"WinsRequired":[2,4,6,8,10,12,14,16,18,20]}},{"id":1,"name":"Ball: Normal","lookup":"ball_lookup","parameters":{"Type":"ball"}},{"id":236,"name":"Reward: Spell - Random Pro (x4)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"1","Amount":4}},{"id":189,"name":"Reward: Chest - Silver Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"3","Amount":0}},{"id":173,"name":"Reward: Gold (x300)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":300}},{"id":237,"name":"Reward: Spell - Random Core (x40)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"0","Amount":40}},{"id":190,"name":"Reward: Chest - Golden Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"4","Amount":0}},{"id":238,"name":"Reward: Gold (x600)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":600}},{"id":228,"name":"Reward: Spell - Random Pro (x16)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"1","Amount":16}},{"id":190,"name":"Reward: Chest - Golden Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"4","Amount":0}},{"id":150,"name":"Reward: Spell - Random Superstar (x1)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"2","Amount":1}},{"id":76,"name":"Reward: Chest - Epic Event Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"18","Amount":0}}]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        // LogicLiveEvent #10
        stream.writeVInt(7131)
        stream.writeStringReference('2v2 - No Goalie - 20W - ZenPalace - EpicChest')
        stream.writeVInt(2)
        stream.writeVInt(1786708800)
        stream.writeVInt(1786880700)
        stream.writeVInt(1786622400)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('2v2 - No Goalie - 20W - ZenPalace - EpicChest')
        stream.writeString('{"Color":"#ae2d13","2V2Lookup":"258","lookupValues":[{"id":258,"name":"2v2 - No Goalie - 20W - ZenPalace - EpicChest","lookup":"2v2_event_lookup","parameters":{"NameKey":"survival-no-goalie-name","DescriptionKey":"survival-no-goalie-desc","GameModeConfig":{"GoaliesDisabled":true,"BallDensity":100,"BallScale":100,"NumberOfBallsOnOvertime":2,"DisableDeckRandomization":false,"ManaGeneration":100,"Arena":7,"NumberOfBalls":1},"BallType":"1","IntermediateRewards":["236","189","173","237","190","238","228","190","150","76"],"WinsRequired":[2,4,6,8,10,12,14,16,18,20]}},{"id":1,"name":"Ball: Normal","lookup":"ball_lookup","parameters":{"Type":"ball"}},{"id":236,"name":"Reward: Spell - Random Pro (x4)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"1","Amount":4}},{"id":189,"name":"Reward: Chest - Silver Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"3","Amount":0}},{"id":173,"name":"Reward: Gold (x300)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":300}},{"id":237,"name":"Reward: Spell - Random Core (x40)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"0","Amount":40}},{"id":190,"name":"Reward: Chest - Golden Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"4","Amount":0}},{"id":238,"name":"Reward: Gold (x600)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":600}},{"id":228,"name":"Reward: Spell - Random Pro (x16)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"1","Amount":16}},{"id":190,"name":"Reward: Chest - Golden Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"4","Amount":0}},{"id":150,"name":"Reward: Spell - Random Superstar (x1)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"2","Amount":1}},{"id":76,"name":"Reward: Chest - Epic Event Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"18","Amount":0}}]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        // LogicLiveEvent #11
        stream.writeVInt(7133)
        stream.writeStringReference('2v2 - Own Lineup - 20W - ElDorado - EventChest')
        stream.writeVInt(2)
        stream.writeVInt(1787140800)
        stream.writeVInt(1787226300)
        stream.writeVInt(1787054400)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('2v2 - Own Lineup - 20W - ElDorado - EventChest')
        stream.writeString('{"Color":"#ae2d13","2V2Lookup":"256","lookupValues":[{"id":256,"name":"2v2 - Own Lineup - 20W - ElDorado - EventChest","lookup":"2v2_event_lookup","parameters":{"NameKey":"survival-2v2-name","DescriptionKey":"survival-2v2-desc-1","GameModeConfig":{"GoaliesDisabled":false,"BallDensity":100,"BallScale":100,"NumberOfBallsOnOvertime":2,"DisableDeckRandomization":false,"ManaGeneration":100,"Arena":4,"NumberOfBalls":1},"BallType":"1","WinsRequired":[2,4,6,8,10,12,14,16,18,20],"IntermediateRewards":["59","6","189","236","189","173","237","11","190","214"]}},{"id":1,"name":"Ball: Normal","lookup":"ball_lookup","parameters":{"Type":"ball"}},{"id":59,"name":"Reward: Spell - Random Core (x5)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"0","Amount":5}},{"id":6,"name":"Reward: Gold (x100)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":100}},{"id":189,"name":"Reward: Chest - Silver Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"3","Amount":0}},{"id":236,"name":"Reward: Spell - Random Pro (x4)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"1","Amount":4}},{"id":189,"name":"Reward: Chest - Silver Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"3","Amount":0}},{"id":173,"name":"Reward: Gold (x300)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":300}},{"id":237,"name":"Reward: Spell - Random Core (x40)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"0","Amount":40}},{"id":11,"name":"Reward: Gold (x500)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":500}},{"id":190,"name":"Reward: Chest - Golden Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"4","Amount":0}},{"id":214,"name":"Reward: Chest - Event Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"39","Amount":0}}]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        // LogicLiveEvent #12
        stream.writeVInt(7134)
        stream.writeStringReference('2v2 - Own Lineup - 20W - ElDorado - EventChest')
        stream.writeVInt(2)
        stream.writeVInt(1787745600)
        stream.writeVInt(1787831100)
        stream.writeVInt(1787659200)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('2v2 - Own Lineup - 20W - ElDorado - EventChest')
        stream.writeString('{"Color":"#ae2d13","2V2Lookup":"256","lookupValues":[{"id":256,"name":"2v2 - Own Lineup - 20W - ElDorado - EventChest","lookup":"2v2_event_lookup","parameters":{"NameKey":"survival-2v2-name","DescriptionKey":"survival-2v2-desc-1","GameModeConfig":{"GoaliesDisabled":false,"BallDensity":100,"BallScale":100,"NumberOfBallsOnOvertime":2,"DisableDeckRandomization":false,"ManaGeneration":100,"Arena":4,"NumberOfBalls":1},"BallType":"1","WinsRequired":[2,4,6,8,10,12,14,16,18,20],"IntermediateRewards":["59","6","189","236","189","173","237","11","190","214"]}},{"id":1,"name":"Ball: Normal","lookup":"ball_lookup","parameters":{"Type":"ball"}},{"id":59,"name":"Reward: Spell - Random Core (x5)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"0","Amount":5}},{"id":6,"name":"Reward: Gold (x100)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":100}},{"id":189,"name":"Reward: Chest - Silver Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"3","Amount":0}},{"id":236,"name":"Reward: Spell - Random Pro (x4)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"1","Amount":4}},{"id":189,"name":"Reward: Chest - Silver Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"3","Amount":0}},{"id":173,"name":"Reward: Gold (x300)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":300}},{"id":237,"name":"Reward: Spell - Random Core (x40)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"0","Amount":40}},{"id":11,"name":"Reward: Gold (x500)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":500}},{"id":190,"name":"Reward: Chest - Golden Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"4","Amount":0}},{"id":214,"name":"Reward: Chest - Event Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"39","Amount":0}}]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        // LogicLiveEvent #13
        stream.writeVInt(7135)
        stream.writeStringReference('2v2 - Boom Rocket Madness - 20W- Greenfield - EventChest')
        stream.writeVInt(2)
        stream.writeVInt(1786968000)
        stream.writeVInt(1787053500)
        stream.writeVInt(1786881600)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('2v2 - Boom Rocket Madness - 20W- Greenfield - EventChest')
        stream.writeString('{"Color":"#ae2d13","2V2Lookup":"259","lookupValues":[{"id":259,"name":"2v2 - Boom Rocket Madness - 20W- Greenfield - EventChest","lookup":"2v2_event_lookup","parameters":{"NameKey":"survival-rocket-name","DescriptionKey":"survival-rocket-desc-2","GameModeConfig":{"GoaliesDisabled":true,"BallDensity":100,"BallScale":100,"NumberOfBallsOnOvertime":4,"DisableDeckRandomization":true,"ManaGeneration":200,"Arena":1,"NumberOfBalls":3},"BallType":"1","Deck":["18","18","18","18"],"IntermediateRewards":["59","6","189","236","189","173","237","11","190","214"],"WinsRequired":[2,4,6,8,10,12,14,16,18,20]}},{"id":1,"name":"Ball: Normal","lookup":"ball_lookup","parameters":{"Type":"ball"}},{"id":18,"name":"Spell: Boom Rocket","lookup":"spell_lookup","parameters":{"RefId":"rocket"}},{"id":18,"name":"Spell: Boom Rocket","lookup":"spell_lookup","parameters":{"RefId":"rocket"}},{"id":18,"name":"Spell: Boom Rocket","lookup":"spell_lookup","parameters":{"RefId":"rocket"}},{"id":18,"name":"Spell: Boom Rocket","lookup":"spell_lookup","parameters":{"RefId":"rocket"}},{"id":59,"name":"Reward: Spell - Random Core (x5)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"0","Amount":5}},{"id":6,"name":"Reward: Gold (x100)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":100}},{"id":189,"name":"Reward: Chest - Silver Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"3","Amount":0}},{"id":236,"name":"Reward: Spell - Random Pro (x4)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"1","Amount":4}},{"id":189,"name":"Reward: Chest - Silver Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"3","Amount":0}},{"id":173,"name":"Reward: Gold (x300)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":300}},{"id":237,"name":"Reward: Spell - Random Core (x40)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"0","Amount":40}},{"id":11,"name":"Reward: Gold (x500)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":500}},{"id":190,"name":"Reward: Chest - Golden Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"4","Amount":0}},{"id":214,"name":"Reward: Chest - Event Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"39","Amount":0}}]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        // LogicLiveEvent #14
        stream.writeVInt(7136)
        stream.writeStringReference('2v2 - Boom Rocket Madness - 20W- Greenfield - EventChest')
        stream.writeVInt(2)
        stream.writeVInt(1787572800)
        stream.writeVInt(1787658300)
        stream.writeVInt(1787486400)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('2v2 - Boom Rocket Madness - 20W- Greenfield - EventChest')
        stream.writeString('{"Color":"#ae2d13","2V2Lookup":"259","lookupValues":[{"id":259,"name":"2v2 - Boom Rocket Madness - 20W- Greenfield - EventChest","lookup":"2v2_event_lookup","parameters":{"NameKey":"survival-rocket-name","DescriptionKey":"survival-rocket-desc-2","GameModeConfig":{"GoaliesDisabled":true,"BallDensity":100,"BallScale":100,"NumberOfBallsOnOvertime":4,"DisableDeckRandomization":true,"ManaGeneration":200,"Arena":1,"NumberOfBalls":3},"BallType":"1","Deck":["18","18","18","18"],"IntermediateRewards":["59","6","189","236","189","173","237","11","190","214"],"WinsRequired":[2,4,6,8,10,12,14,16,18,20]}},{"id":1,"name":"Ball: Normal","lookup":"ball_lookup","parameters":{"Type":"ball"}},{"id":18,"name":"Spell: Boom Rocket","lookup":"spell_lookup","parameters":{"RefId":"rocket"}},{"id":18,"name":"Spell: Boom Rocket","lookup":"spell_lookup","parameters":{"RefId":"rocket"}},{"id":18,"name":"Spell: Boom Rocket","lookup":"spell_lookup","parameters":{"RefId":"rocket"}},{"id":18,"name":"Spell: Boom Rocket","lookup":"spell_lookup","parameters":{"RefId":"rocket"}},{"id":59,"name":"Reward: Spell - Random Core (x5)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"0","Amount":5}},{"id":6,"name":"Reward: Gold (x100)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":100}},{"id":189,"name":"Reward: Chest - Silver Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"3","Amount":0}},{"id":236,"name":"Reward: Spell - Random Pro (x4)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"1","Amount":4}},{"id":189,"name":"Reward: Chest - Silver Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"3","Amount":0}},{"id":173,"name":"Reward: Gold (x300)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":300}},{"id":237,"name":"Reward: Spell - Random Core (x40)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"0","Amount":40}},{"id":11,"name":"Reward: Gold (x500)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":500}},{"id":190,"name":"Reward: Chest - Golden Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"4","Amount":0}},{"id":214,"name":"Reward: Chest - Event Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"39","Amount":0}}]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        // LogicLiveEvent #15
        stream.writeVInt(7139)
        stream.writeStringReference('Cup: (2022) Own Line UP 16p')
        stream.writeVInt(4)
        stream.writeVInt(1787572800)
        stream.writeVInt(1787831100)
        stream.writeVInt(1787486400)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Cup: (2022) Own Line UP 16p')
        stream.writeString('{"Color":"#ae2d13","CupLookup":"374","lookupValues":[{"id":374,"name":"Cup - (2022) Own Lineup - 16P - Greenfield - SuperEventChest","lookup":"cup_event_lookup","parameters":{"JoinCost":20,"FreeEntriesCount":0,"PlayerCount":16,"GameModeConfig":{"GoaliesDisabled":false,"BallDensity":100,"BallScale":100,"NumberOfBallsOnOvertime":2,"DisableDeckRandomization":false,"ManaGeneration":100,"Arena":4,"NumberOfBalls":1},"BallType":"1","IntermediateRewards":["11","114","201"],"EndRewards":["190","74","214"],"FinalReward":"75","NameKey":"survival-generic1-name","DescriptionKey":"survival-generic4-desc"}},{"id":1,"name":"Ball: Normal","lookup":"ball_lookup","parameters":{"Type":"ball"}},{"id":11,"name":"Reward: Gold (x500)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":500}},{"id":114,"name":"Reward: Gold (x1000)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":1000}},{"id":201,"name":"Reward: Gold (x1500)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":1500}},{"id":190,"name":"Reward: Chest - Golden Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"4","Amount":0}},{"id":74,"name":"Reward: Chest - Mini Event Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"16","Amount":0}},{"id":214,"name":"Reward: Chest - Event Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"39","Amount":0}},{"id":75,"name":"Reward: Chest - Rare Event Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"17","Amount":0}}]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        // LogicLiveEvent #16
        stream.writeVInt(7141)
        stream.writeStringReference('Gift: Weekend Gift (Gems x100)')
        stream.writeVInt(9)
        stream.writeVInt(1786795200)
        stream.writeVInt(1786880700)
        stream.writeVInt(1786795200)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Gift: Weekend Gift (Gems x100)')
        stream.writeString('{"Color":"#ae2d13","Title":"chronos-gift-gems-description-2","Description":"chronos-gift-gems-description","DonationReward":"115","lookupValues":[{"id":115,"name":"Reward: Gems (x100)","lookup":"reward_lookup","parameters":{"Type":"Gems","RefId":"-1","Amount":100}}]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        // LogicLiveEvent #17
        stream.writeVInt(7143)
        stream.writeStringReference('Survival - Gold Rush - 10W3L - ZenPalace - EpicChest')
        stream.writeVInt(1)
        stream.writeVInt(1786708800)
        stream.writeVInt(1786880700)
        stream.writeVInt(1786622400)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Survival - Gold Rush - 10W3L - ZenPalace - EpicChest')
        stream.writeString('{"Color":"#ae2d13","SurvivalLookup":"147","2v2":false,"lookupValues":[{"id":147,"name":"Survival - Gold Rush - 10W3L - ZenPalace - EpicChest","lookup":"survival_event_lookup","parameters":{"JoinCost":40,"FreePass":1,"MaxWins":10,"MaxLoss":3,"ManaGeneration":100,"BallDensity":100,"BallScale":100,"NumberOfBalls":1,"NumberOfBallsOnOvertime":2,"ResetWinsOnRetry":false,"NameKey":"survival-gold-rush-name","DescriptionKey":"survival-gold-rush-desc","Arena":7,"BallType":"1","EndRewardChest":"76","IntermediateRewards":["6","8","173","203","11","238","239","114","13"],"GoaliesDisabled":false,"AllowPlayingAfterWin":false,"DisableDeckRandomization":false}},{"id":1,"name":"Ball: Normal","lookup":"ball_lookup","parameters":{"Type":"ball"}},{"id":76,"name":"Reward: Chest - Epic Event Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"18","Amount":0}},{"id":6,"name":"Reward: Gold (x100)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":100}},{"id":8,"name":"Reward: Gold (x200)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":200}},{"id":173,"name":"Reward: Gold (x300)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":300}},{"id":203,"name":"Reward: Gold (x400)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":400}},{"id":11,"name":"Reward: Gold (x500)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":500}},{"id":238,"name":"Reward: Gold (x600)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":600}},{"id":239,"name":"Reward: Gold (x800)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":800}},{"id":114,"name":"Reward: Gold (x1000)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":1000}},{"id":13,"name":"Reward: Gold (x1200)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":1200}}]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        // LogicLiveEvent #18
        stream.writeVInt(7144)
        stream.writeStringReference('Survival: (2022) Zen Mayhem 10W 3L')
        stream.writeVInt(1)
        stream.writeVInt(1786968000)
        stream.writeVInt(1787053500)
        stream.writeVInt(1786881600)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Survival: (2022) Zen Mayhem 10W 3L')
        stream.writeString('{"Color":"#ae2d13","SurvivalLookup":"387","2v2":false,"lookupValues":[{"id":387,"name":"Survival - (2022) Zen Mayhem - 10W3L - Greenfield - EventChest","lookup":"survival_event_lookup","parameters":{"JoinCost":20,"FreePass":1,"MaxWins":10,"MaxLoss":3,"ManaGeneration":200,"BallDensity":100,"BallScale":100,"NumberOfBalls":2,"NumberOfBallsOnOvertime":3,"ResetWinsOnRetry":false,"NameKey":"survival-koala-name-3","DescriptionKey":"survival-generic3-desc","Arena":1,"GoaliesDisabled":true,"DisableDeckRandomization":false,"BallType":"1","EndRewardChest":"214","Deck":["56","46","49","20","43","44","45","41"],"IntermediateRewards":["59","6","189","236","189","173","237","11","190"],"AllowPlayingAfterWin":false}},{"id":1,"name":"Ball: Normal","lookup":"ball_lookup","parameters":{"Type":"ball"}},{"id":214,"name":"Reward: Chest - Event Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"39","Amount":0}},{"id":56,"name":"Spell: Turtle Spinner","lookup":"spell_lookup","parameters":{"RefId":"turtle"}},{"id":46,"name":"Spell: Mr. Mine","lookup":"spell_lookup","parameters":{"RefId":"mine"}},{"id":49,"name":"Spell: Royal Dung","lookup":"spell_lookup","parameters":{"RefId":"dung"}},{"id":20,"name":"Spell: Bouncy Board","lookup":"spell_lookup","parameters":{"RefId":"springboard"}},{"id":43,"name":"Spell: Melon","lookup":"spell_lookup","parameters":{"RefId":"melon"}},{"id":44,"name":"Spell: Mr. Bigshot","lookup":"spell_lookup","parameters":{"RefId":"shotgun"}},{"id":45,"name":"Spell: Mr. Fire","lookup":"spell_lookup","parameters":{"RefId":"explosive"}},{"id":41,"name":"Spell: Magnetman","lookup":"spell_lookup","parameters":{"RefId":"magnet"}},{"id":59,"name":"Reward: Spell - Random Core (x5)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"0","Amount":5}},{"id":6,"name":"Reward: Gold (x100)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":100}},{"id":189,"name":"Reward: Chest - Silver Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"3","Amount":0}},{"id":236,"name":"Reward: Spell - Random Pro (x4)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"1","Amount":4}},{"id":189,"name":"Reward: Chest - Silver Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"3","Amount":0}},{"id":173,"name":"Reward: Gold (x300)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":300}},{"id":237,"name":"Reward: Spell - Random Core (x40)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"0","Amount":40}},{"id":11,"name":"Reward: Gold (x500)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":500}},{"id":190,"name":"Reward: Chest - Golden Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"4","Amount":0}}]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        // LogicLiveEvent #19
        stream.writeVInt(7145)
        stream.writeStringReference('Survival - Tiger Special Challenge - 8W3L - Greenfield - RareChest/Tiger')
        stream.writeVInt(1)
        stream.writeVInt(1787140800)
        stream.writeVInt(1787226300)
        stream.writeVInt(1787054400)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Survival - Tiger Special Challenge - 8W3L - Greenfield - RareChest/Tiger')
        stream.writeString('{"Color":"#ae2d13","SurvivalLookup":"246","2v2":false,"lookupValues":[{"id":246,"name":"Survival - Special Challenge Striker Tiger - 10W3L - Greenfield - RareChest/Tiger","lookup":"survival_event_lookup","parameters":{"JoinCost":30,"FreePass":1,"MaxWins":10,"MaxLoss":3,"ManaGeneration":150,"BallDensity":100,"BallScale":100,"NumberOfBalls":1,"NumberOfBallsOnOvertime":2,"ResetWinsOnRetry":false,"NameKey":"survival-specialchallenge-attacker-name","DescriptionKey":"survival-attacker-desc","Arena":1,"GoaliesDisabled":false,"DisableDeckRandomization":false,"BallType":"1","EndRewardChest":"75","Deck":["54","19","39","16","36","43","56","28"],"IntermediateRewards":["189","7","212","189","205","189","190","211","150"],"AllowPlayingAfterWin":false,"EndRewardSpecificSpell":"241"}},{"id":1,"name":"Ball: Normal","lookup":"ball_lookup","parameters":{"Type":"ball"}},{"id":75,"name":"Reward: Chest - Rare Event Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"17","Amount":0}},{"id":54,"name":"Spell: Striker Tiger","lookup":"spell_lookup","parameters":{"RefId":"attacker"}},{"id":19,"name":"Spell: Bouncer Bear","lookup":"spell_lookup","parameters":{"RefId":"bear"}},{"id":39,"name":"Spell: Lover","lookup":"spell_lookup","parameters":{"RefId":"lover"}},{"id":16,"name":"Spell: Bomba","lookup":"spell_lookup","parameters":{"RefId":"bomb"}},{"id":36,"name":"Spell: Lazy Panda","lookup":"spell_lookup","parameters":{"RefId":"pawn"}},{"id":43,"name":"Spell: Melon","lookup":"spell_lookup","parameters":{"RefId":"melon"}},{"id":56,"name":"Spell: Turtle Spinner","lookup":"spell_lookup","parameters":{"RefId":"turtle"}},{"id":28,"name":"Spell: Fan","lookup":"spell_lookup","parameters":{"RefId":"fan"}},{"id":189,"name":"Reward: Chest - Silver Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"3","Amount":0}},{"id":7,"name":"Reward: Gold (x150)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":150}},{"id":212,"name":"Reward: Spell - Random Core (x25)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"0","Amount":25}},{"id":189,"name":"Reward: Chest - Silver Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"3","Amount":0}},{"id":205,"name":"Reward: Spell - Random Pro (x8)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"1","Amount":8}},{"id":189,"name":"Reward: Chest - Silver Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"3","Amount":0}},{"id":190,"name":"Reward: Chest - Golden Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"4","Amount":0}},{"id":211,"name":"Reward: Spell - Random Core (x75)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"0","Amount":75}},{"id":150,"name":"Reward: Spell - Random Superstar (x1)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"2","Amount":1}},{"id":241,"name":"Reward: Spell - Striker Tiger (x10)","lookup":"reward_lookup","parameters":{"Type":"SpellSpecific","RefId":"attacker","Amount":10}}]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        // LogicLiveEvent #20
        stream.writeVInt(7146)
        stream.writeStringReference('Survival - Triple Energy Rush - 10W3L - ElDorado - EventChest')
        stream.writeVInt(1)
        stream.writeVInt(1786622400)
        stream.writeVInt(1786707900)
        stream.writeVInt(1786536000)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Survival - Triple Energy Rush - 10W3L - ElDorado - EventChest')
        stream.writeString('{"Color":"#ae2d13","SurvivalLookup":"93","2v2":false,"lookupValues":[{"id":93,"name":"Survival - Triple Energy Rush - 10W3L - El Dorado - EventChest","lookup":"survival_event_lookup","parameters":{"JoinCost":20,"FreePass":1,"MaxWins":10,"MaxLoss":3,"ManaGeneration":300,"BallDensity":100,"BallScale":100,"NumberOfBalls":1,"NumberOfBallsOnOvertime":2,"ResetWinsOnRetry":false,"NameKey":"survival-triple-energy-rush-name","DescriptionKey":"survival-triple-energy-rush-desc","Arena":4,"BallType":"1","EndRewardChest":"214","IntermediateRewards":["59","6","189","236","189","173","237","11","190"],"GoaliesDisabled":false,"AllowPlayingAfterWin":false,"DisableDeckRandomization":false}},{"id":1,"name":"Ball: Normal","lookup":"ball_lookup","parameters":{"Type":"ball"}},{"id":214,"name":"Reward: Chest - Event Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"39","Amount":0}},{"id":59,"name":"Reward: Spell - Random Core (x5)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"0","Amount":5}},{"id":6,"name":"Reward: Gold (x100)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":100}},{"id":189,"name":"Reward: Chest - Silver Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"3","Amount":0}},{"id":236,"name":"Reward: Spell - Random Pro (x4)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"1","Amount":4}},{"id":189,"name":"Reward: Chest - Silver Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"3","Amount":0}},{"id":173,"name":"Reward: Gold (x300)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":300}},{"id":237,"name":"Reward: Spell - Random Core (x40)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"0","Amount":40}},{"id":11,"name":"Reward: Gold (x500)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":500}},{"id":190,"name":"Reward: Chest - Golden Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"4","Amount":0}}]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        // LogicLiveEvent #21
        stream.writeVInt(7147)
        stream.writeStringReference('Survival - Triple Energy Rush - 10W3L - ElDorado - EventChest')
        stream.writeVInt(1)
        stream.writeVInt(1787227200)
        stream.writeVInt(1787312700)
        stream.writeVInt(1787140800)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Survival - Triple Energy Rush - 10W3L - ElDorado - EventChest')
        stream.writeString('{"Color":"#ae2d13","SurvivalLookup":"93","2v2":false,"lookupValues":[{"id":93,"name":"Survival - Triple Energy Rush - 10W3L - El Dorado - EventChest","lookup":"survival_event_lookup","parameters":{"JoinCost":20,"FreePass":1,"MaxWins":10,"MaxLoss":3,"ManaGeneration":300,"BallDensity":100,"BallScale":100,"NumberOfBalls":1,"NumberOfBallsOnOvertime":2,"ResetWinsOnRetry":false,"NameKey":"survival-triple-energy-rush-name","DescriptionKey":"survival-triple-energy-rush-desc","Arena":4,"BallType":"1","EndRewardChest":"214","IntermediateRewards":["59","6","189","236","189","173","237","11","190"],"GoaliesDisabled":false,"AllowPlayingAfterWin":false,"DisableDeckRandomization":false}},{"id":1,"name":"Ball: Normal","lookup":"ball_lookup","parameters":{"Type":"ball"}},{"id":214,"name":"Reward: Chest - Event Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"39","Amount":0}},{"id":59,"name":"Reward: Spell - Random Core (x5)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"0","Amount":5}},{"id":6,"name":"Reward: Gold (x100)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":100}},{"id":189,"name":"Reward: Chest - Silver Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"3","Amount":0}},{"id":236,"name":"Reward: Spell - Random Pro (x4)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"1","Amount":4}},{"id":189,"name":"Reward: Chest - Silver Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"3","Amount":0}},{"id":173,"name":"Reward: Gold (x300)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":300}},{"id":237,"name":"Reward: Spell - Random Core (x40)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"0","Amount":40}},{"id":11,"name":"Reward: Gold (x500)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":500}},{"id":190,"name":"Reward: Chest - Golden Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"4","Amount":0}}]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        // LogicLiveEvent #22
        stream.writeVInt(7148)
        stream.writeStringReference('Survival - Explosive Madness - 10W3L - Greenfield - EventChest')
        stream.writeVInt(1)
        stream.writeVInt(1786881600)
        stream.writeVInt(1786967100)
        stream.writeVInt(1786795200)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Survival - Explosive Madness - 10W3L - Greenfield - EventChest')
        stream.writeString('{"Color":"#ae2d13","SurvivalLookup":"123","2v2":false,"lookupValues":[{"id":123,"name":"Survival - Explosive Madness - 10W3L - Greenfield - EventChest","lookup":"survival_event_lookup","parameters":{"JoinCost":20,"FreePass":1,"MaxWins":10,"MaxLoss":3,"ManaGeneration":200,"BallDensity":100,"BallScale":100,"NumberOfBalls":3,"NumberOfBallsOnOvertime":4,"ResetWinsOnRetry":false,"NameKey":"survival-explosion-mayhem-name","DescriptionKey":"survival-explosion-mayhem-desc","Arena":1,"GoaliesDisabled":true,"DisableDeckRandomization":true,"BallType":"1","EndRewardChest":"214","Deck":["45","45","45","45"],"IntermediateRewards":["59","6","189","236","189","173","237","11","190"],"AllowPlayingAfterWin":false}},{"id":1,"name":"Ball: Normal","lookup":"ball_lookup","parameters":{"Type":"ball"}},{"id":214,"name":"Reward: Chest - Event Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"39","Amount":0}},{"id":45,"name":"Spell: Mr. Fire","lookup":"spell_lookup","parameters":{"RefId":"explosive"}},{"id":45,"name":"Spell: Mr. Fire","lookup":"spell_lookup","parameters":{"RefId":"explosive"}},{"id":45,"name":"Spell: Mr. Fire","lookup":"spell_lookup","parameters":{"RefId":"explosive"}},{"id":45,"name":"Spell: Mr. Fire","lookup":"spell_lookup","parameters":{"RefId":"explosive"}},{"id":59,"name":"Reward: Spell - Random Core (x5)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"0","Amount":5}},{"id":6,"name":"Reward: Gold (x100)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":100}},{"id":189,"name":"Reward: Chest - Silver Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"3","Amount":0}},{"id":236,"name":"Reward: Spell - Random Pro (x4)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"1","Amount":4}},{"id":189,"name":"Reward: Chest - Silver Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"3","Amount":0}},{"id":173,"name":"Reward: Gold (x300)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":300}},{"id":237,"name":"Reward: Spell - Random Core (x40)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"0","Amount":40}},{"id":11,"name":"Reward: Gold (x500)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":500}},{"id":190,"name":"Reward: Chest - Golden Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"4","Amount":0}}]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        // LogicLiveEvent #23
        stream.writeVInt(7149)
        stream.writeStringReference('Survival - Training Plains Showdown - 10W3L - Greenfield - EventChest')
        stream.writeVInt(1)
        stream.writeVInt(1787054400)
        stream.writeVInt(1787139900)
        stream.writeVInt(1786968000)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Survival - Training Plains Showdown - 10W3L - Greenfield - EventChest')
        stream.writeString('{"Color":"#ae2d13","SurvivalLookup":"131","2v2":false,"lookupValues":[{"id":131,"name":"Survival - Training Plains Showdown - 10W3L - Greenfield - EventChest","lookup":"survival_event_lookup","parameters":{"JoinCost":20,"FreePass":1,"MaxWins":10,"MaxLoss":3,"ManaGeneration":100,"BallDensity":100,"BallScale":100,"NumberOfBalls":1,"NumberOfBallsOnOvertime":2,"ResetWinsOnRetry":false,"Arena":0,"NameKey":"survival-training-plains-showdown-name","DescriptionKey":"survival-training-plains-showdown-desc","BallType":"1","EndRewardChest":"214","Deck":["36","45","54","41","47","51","40","21"],"IntermediateRewards":["59","6","189","236","189","173","237","11","190"],"GoaliesDisabled":false,"AllowPlayingAfterWin":false,"DisableDeckRandomization":false}},{"id":1,"name":"Ball: Normal","lookup":"ball_lookup","parameters":{"Type":"ball"}},{"id":214,"name":"Reward: Chest - Event Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"39","Amount":0}},{"id":36,"name":"Spell: Lazy Panda","lookup":"spell_lookup","parameters":{"RefId":"pawn"}},{"id":45,"name":"Spell: Mr. Fire","lookup":"spell_lookup","parameters":{"RefId":"explosive"}},{"id":54,"name":"Spell: Striker Tiger","lookup":"spell_lookup","parameters":{"RefId":"attacker"}},{"id":41,"name":"Spell: Magnetman","lookup":"spell_lookup","parameters":{"RefId":"magnet"}},{"id":47,"name":"Spell: Raging Bull","lookup":"spell_lookup","parameters":{"RefId":"bull"}},{"id":51,"name":"Spell: Sniper Wolf","lookup":"spell_lookup","parameters":{"RefId":"sniper"}},{"id":40,"name":"Spell: Loyal Dog","lookup":"spell_lookup","parameters":{"RefId":"support"}},{"id":21,"name":"Spell: Cannonman","lookup":"spell_lookup","parameters":{"RefId":"cannon"}},{"id":59,"name":"Reward: Spell - Random Core (x5)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"0","Amount":5}},{"id":6,"name":"Reward: Gold (x100)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":100}},{"id":189,"name":"Reward: Chest - Silver Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"3","Amount":0}},{"id":236,"name":"Reward: Spell - Random Pro (x4)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"1","Amount":4}},{"id":189,"name":"Reward: Chest - Silver Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"3","Amount":0}},{"id":173,"name":"Reward: Gold (x300)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":300}},{"id":237,"name":"Reward: Spell - Random Core (x40)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"0","Amount":40}},{"id":11,"name":"Reward: Gold (x500)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":500}},{"id":190,"name":"Reward: Chest - Golden Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"4","Amount":0}}]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        // LogicLiveEvent #24
        stream.writeVInt(7150)
        stream.writeStringReference('Survival - Special Challenge Hipdozer - 12W3L - El Dorado - EpicChest/Hipdozer')
        stream.writeVInt(1)
        stream.writeVInt(1787313600)
        stream.writeVInt(1787485500)
        stream.writeVInt(1787227200)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Survival - Special Challenge Hipdozer - 12W3L - El Dorado - EpicChest/Hipdozer')
        stream.writeString('{"Color":"#ae2d13","SurvivalLookup":"226","2v2":false,"lookupValues":[{"id":226,"name":"Survival - Special Challenge Hipdozer - 12W3L - El Dorado - EpicChest/Hipdozer","lookup":"survival_event_lookup","parameters":{"JoinCost":50,"FreePass":1,"MaxWins":12,"MaxLoss":3,"ManaGeneration":150,"BallDensity":100,"BallScale":100,"NumberOfBalls":1,"NumberOfBallsOnOvertime":2,"ResetWinsOnRetry":false,"NameKey":"survival-specialchallenge-hippo-name","DescriptionKey":"survival-hippo-desc","Arena":4,"GoaliesDisabled":false,"DisableDeckRandomization":false,"BallType":"1","EndRewardChest":"76","Deck":["34","52","40","22","43","26","37","20"],"IntermediateRewards":["60","8","189","67","189","114","190","210","192","150","72"],"AllowPlayingAfterWin":false,"EndRewardSpecificSpell":"222"}},{"id":1,"name":"Ball: Normal","lookup":"ball_lookup","parameters":{"Type":"ball"}},{"id":76,"name":"Reward: Chest - Epic Event Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"18","Amount":0}},{"id":34,"name":"Spell: Hipdozer","lookup":"spell_lookup","parameters":{"RefId":"hippo"}},{"id":52,"name":"Spell: Sticky Puffer","lookup":"spell_lookup","parameters":{"RefId":"puffer"}},{"id":40,"name":"Spell: Loyal Dog","lookup":"spell_lookup","parameters":{"RefId":"support"}},{"id":22,"name":"Spell: Crazy Cat","lookup":"spell_lookup","parameters":{"RefId":"cat"}},{"id":43,"name":"Spell: Melon","lookup":"spell_lookup","parameters":{"RefId":"melon"}},{"id":26,"name":"Spell: Energy Pump","lookup":"spell_lookup","parameters":{"RefId":"manapump"}},{"id":37,"name":"Spell: Leeches","lookup":"spell_lookup","parameters":{"RefId":"leeches"}},{"id":20,"name":"Spell: Bouncy Board","lookup":"spell_lookup","parameters":{"RefId":"springboard"}},{"id":60,"name":"Reward: Spell - Random Core (x10)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"0","Amount":10}},{"id":8,"name":"Reward: Gold (x200)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":200}},{"id":189,"name":"Reward: Chest - Silver Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"3","Amount":0}},{"id":67,"name":"Reward: Spell - Random Pro (x12)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"1","Amount":12}},{"id":189,"name":"Reward: Chest - Silver Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"3","Amount":0}},{"id":114,"name":"Reward: Gold (x1000)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":1000}},{"id":190,"name":"Reward: Chest - Golden Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"4","Amount":0}},{"id":210,"name":"Reward: Spell - Random Core (x125)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"0","Amount":125}},{"id":192,"name":"Reward: Gold (x2000)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":2000}},{"id":150,"name":"Reward: Spell - Random Superstar (x1)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"2","Amount":1}},{"id":72,"name":"Reward: Chest - Colossal Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"5","Amount":0}},{"id":222,"name":"Reward: Spell - Hipdozer (x5)","lookup":"reward_lookup","parameters":{"Type":"SpellSpecific","RefId":"hippo","Amount":5}}]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        // LogicLiveEvent #25
        stream.writeVInt(7151)
        stream.writeStringReference('Offer - Stock up for End of Season - season-2 (Booster C)')
        stream.writeVInt(0)
        stream.writeVInt(1786839300)
        stream.writeVInt(1787011140)
        stream.writeVInt(1786839300)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Offer - Stock up for End of Season - season-2 (Booster C)')
        stream.writeString('{"Color":"#448932","ShopSpenderDaysInActive":7,"ShopSpenderPercentageIncrease":50,"ShopSpenderCapWeekly":true,"ShopSpenderCapMonthly":true,"ShopSpenderCapAllTime":true,"OverrideName":"chronos-special-offer-season-2","TierDefaultShopItem":"7003020","Tier1ShopItem":"7003010","Tier2ShopItem":"7003010","Tier3ShopItem":"7003010","Tier4ShopItem":"7003010","Tier5ShopItem":"7003010","Tier6ShopItem":"7003010","Tier7ShopItem":"7003010","Tier8ShopItem":"7003010","Tier9ShopItem":"7003010","Tier10ShopItem":"7003010","Tier15ShopItem":"7003015","Tier20ShopItem":"7003020","Tier50ShopItem":"7003050","Tier60ShopItem":"7003060","lookupValues":[]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        // LogicLiveEvent #26
        stream.writeVInt(7152)
        stream.writeStringReference('Offer - Power Up with This! - boost-4 (Booster C)')
        stream.writeVInt(0)
        stream.writeVInt(1787012100)
        stream.writeVInt(1787183940)
        stream.writeVInt(1787012100)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Offer - Power Up with This! - boost-4 (Booster C)')
        stream.writeString('{"Color":"#448932","ShopSpenderDaysInActive":7,"ShopSpenderPercentageIncrease":50,"ShopSpenderCapWeekly":true,"ShopSpenderCapMonthly":true,"ShopSpenderCapAllTime":true,"OverrideName":"chronos-special-offer-boost-4","TierDefaultShopItem":"7003020","Tier1ShopItem":"7003010","Tier2ShopItem":"7003010","Tier3ShopItem":"7003010","Tier4ShopItem":"7003010","Tier5ShopItem":"7003010","Tier6ShopItem":"7003010","Tier7ShopItem":"7003010","Tier8ShopItem":"7003010","Tier9ShopItem":"7003010","Tier10ShopItem":"7003010","Tier15ShopItem":"7003015","Tier20ShopItem":"7003020","Tier50ShopItem":"7003050","Tier60ShopItem":"7003060","lookupValues":[]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        // LogicLiveEvent #27
        stream.writeVInt(7154)
        stream.writeStringReference('Offer - Stock up on Gold - Goldrush-2 (NOBLE A) ')
        stream.writeVInt(0)
        stream.writeVInt(1787184900)
        stream.writeVInt(1787356740)
        stream.writeVInt(1787184900)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Offer - Stock up on Gold - Goldrush-2 (NOBLE A) ')
        stream.writeString('{"Color":"#448932","ShopSpenderDaysInActive":7,"ShopSpenderPercentageIncrease":50,"ShopSpenderCapWeekly":true,"ShopSpenderCapMonthly":true,"ShopSpenderCapAllTime":true,"TierDefaultShopItem":"7019005","Tier1ShopItem":"7001001","Tier2ShopItem":"7019002","Tier3ShopItem":"7019003","Tier4ShopItem":"7019003","Tier5ShopItem":"7019005","Tier6ShopItem":"7019005","Tier7ShopItem":"7019007","Tier8ShopItem":"7019007","Tier9ShopItem":"7019007","Tier10ShopItem":"7019010","Tier15ShopItem":"7019015","Tier20ShopItem":"7019020","Tier50ShopItem":"7019050","Tier60ShopItem":"7019060","OverrideName":"chronos-special-offer-goldrush-2","lookupValues":[]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        // LogicLiveEvent #28
        stream.writeVInt(7155)
        stream.writeStringReference('Offer: Hero Chest C - 7 - "football-9"')
        stream.writeVInt(0)
        stream.writeVInt(1787357700)
        stream.writeVInt(1787529540)
        stream.writeVInt(1787357700)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Offer: Hero Chest C - 7 - "football-9"')
        stream.writeString('{"Color":"#448932","ShopSpenderDaysInActive":7,"ShopSpenderPercentageIncrease":50,"ShopSpenderCapWeekly":true,"ShopSpenderCapMonthly":true,"ShopSpenderCapAllTime":true,"OverrideName":"chronos-special-offer-football-9","TierDefaultShopItem":"7016007","Tier1ShopItem":"7016007","Tier2ShopItem":"7016007","Tier3ShopItem":"7016007","Tier4ShopItem":"7016007","Tier5ShopItem":"7016007","Tier6ShopItem":"7016007","Tier7ShopItem":"7016007","Tier8ShopItem":"7016007","Tier9ShopItem":"7016007","Tier10ShopItem":"7016010","Tier15ShopItem":"7016015","Tier20ShopItem":"7016020","Tier50ShopItem":"7016050","Tier60ShopItem":"7016060","lookupValues":[]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        // LogicLiveEvent #29
        stream.writeVInt(7157)
        stream.writeStringReference('Offer - An Offer Full Of Love - love-1 (Gift A)')
        stream.writeVInt(0)
        stream.writeVInt(1787530500)
        stream.writeVInt(1787702340)
        stream.writeVInt(1787530500)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Offer - An Offer Full Of Love - love-1 (Gift A)')
        stream.writeString('{"Color":"#448932","ShopSpenderDaysInActive":7,"ShopSpenderPercentageIncrease":50,"ShopSpenderCapWeekly":true,"ShopSpenderCapMonthly":true,"ShopSpenderCapAllTime":true,"OverrideName":"chronos-special-offer-love-1","TierDefaultShopItem":"7004010","Tier1ShopItem":"7004001","Tier2ShopItem":"7004002","Tier3ShopItem":"7004003","Tier4ShopItem":"7004003","Tier5ShopItem":"7004005","Tier6ShopItem":"7004005","Tier7ShopItem":"7004007","Tier8ShopItem":"7004007","Tier9ShopItem":"7004007","Tier10ShopItem":"7004010","Tier15ShopItem":"7004015","Tier20ShopItem":"7004020","Tier50ShopItem":"7004050","Tier60ShopItem":"7004060","lookupValues":[]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        // LogicLiveEvent #30
        stream.writeVInt(7159)
        stream.writeStringReference('Gold Battle Chest')
        stream.writeVInt(3)
        stream.writeVInt(1787140800)
        stream.writeVInt(1787226300)
        stream.writeVInt(1787140800)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Gold Battle Chest')
        stream.writeString('{"GlobalEventMode":"1","Color":"#ffba00","lookupValues":[]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        // LogicLiveEvent #31
        stream.writeVInt(7161)
        stream.writeStringReference('Cup - (2022) Bowling Showdown - 32P - Greenfield - Rare Event Chest')
        stream.writeVInt(4)
        stream.writeVInt(1786622400)
        stream.writeVInt(1786794300)
        stream.writeVInt(1786536000)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Cup - (2022) Bowling Showdown - 32P - Greenfield - Rare Event Chest')
        stream.writeString('{"Color":"#ae2d13","CupLookup":"386","lookupValues":[{"id":386,"name":"Cup - (2022) Bowling Showdown - 32P - El Dorado - Rare Event Chest","lookup":"cup_event_lookup","parameters":{"JoinCost":100,"FreeEntriesCount":0,"PlayerCount":32,"GameModeConfig":{"GoaliesDisabled":false,"BallDensity":100,"BallScale":100,"NumberOfBallsOnOvertime":2,"DisableDeckRandomization":false,"ManaGeneration":100,"Arena":4,"NumberOfBalls":1},"BallType":"3","IntermediateRewards":["194","195","379","380"],"EndRewards":["190","74","214","75"],"FinalReward":"76","NameKey":"survival-bowling-showdown-name","DescriptionKey":"survival-rumble-showdown-desc"}},{"id":3,"name":"Ball: Bowling ball","lookup":"ball_lookup","parameters":{"Type":"bowlingball"}},{"id":194,"name":"Reward: Gold (x4000)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":4000}},{"id":195,"name":"Reward: Gold (x5000)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":5000}},{"id":379,"name":"Reward: Gold (x6000)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":6000}},{"id":380,"name":"Reward: Gold (x7000)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":7000}},{"id":190,"name":"Reward: Chest - Golden Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"4","Amount":0}},{"id":74,"name":"Reward: Chest - Mini Event Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"16","Amount":0}},{"id":214,"name":"Reward: Chest - Event Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"39","Amount":0}},{"id":75,"name":"Reward: Chest - Rare Event Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"17","Amount":0}},{"id":76,"name":"Reward: Chest - Epic Event Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"18","Amount":0}}]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        // LogicLiveEvent #32
        stream.writeVInt(7162)
        stream.writeStringReference('Cup - (2022) Bowling Showdown - 8P')
        stream.writeVInt(4)
        stream.writeVInt(1787400000)
        stream.writeVInt(1787571900)
        stream.writeVInt(1787313600)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Cup - (2022) Bowling Showdown - 8P')
        stream.writeString('{"Color":"#ae2d13","CupLookup":"384","lookupValues":[{"id":384,"name":"Cup - (2022) Bowling Showdown - 8P - El Dorado - Mini Event Chest","lookup":"cup_event_lookup","parameters":{"JoinCost":10,"FreeEntriesCount":0,"PlayerCount":8,"GameModeConfig":{"GoaliesDisabled":false,"BallDensity":100,"BallScale":100,"NumberOfBallsOnOvertime":2,"DisableDeckRandomization":false,"ManaGeneration":100,"Arena":4,"NumberOfBalls":1},"BallType":"3","IntermediateRewards":["9","12"],"EndRewards":["190","74"],"FinalReward":"214","NameKey":"survival-bowling-showdown-name","DescriptionKey":"survival-rumble-showdown-desc"}},{"id":3,"name":"Ball: Bowling ball","lookup":"ball_lookup","parameters":{"Type":"bowlingball"}},{"id":9,"name":"Reward: Gold (x250)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":250}},{"id":12,"name":"Reward: Gold (x750)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":750}},{"id":190,"name":"Reward: Chest - Golden Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"4","Amount":0}},{"id":74,"name":"Reward: Chest - Mini Event Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"16","Amount":0}},{"id":214,"name":"Reward: Chest - Event Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"39","Amount":0}}]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        // LogicLiveEvent #33
        stream.writeVInt(7164)
        stream.writeStringReference('Cup: (2022) Beach Ball 16p')
        stream.writeVInt(4)
        stream.writeVInt(1786968000)
        stream.writeVInt(1787226300)
        stream.writeVInt(1786881600)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Cup: (2022) Beach Ball 16p')
        stream.writeString('{"Color":"#ae2d13","CupLookup":"382","lookupValues":[{"id":382,"name":"Cup - (2022) Beach Ball Showdown - 16P - Greenfield - Event Chest","lookup":"cup_event_lookup","parameters":{"JoinCost":20,"FreeEntriesCount":0,"PlayerCount":16,"GameModeConfig":{"GoaliesDisabled":false,"BallDensity":100,"BallScale":100,"NumberOfBallsOnOvertime":2,"DisableDeckRandomization":false,"ManaGeneration":100,"Arena":1,"NumberOfBalls":1},"BallType":"2","IntermediateRewards":["11","114","201"],"EndRewards":["190","74","214"],"FinalReward":"75","NameKey":"survival-beachball-showdown-name","DescriptionKey":"survival-generic4-desc"}},{"id":2,"name":"Ball: Beach ball","lookup":"ball_lookup","parameters":{"Type":"beachball"}},{"id":11,"name":"Reward: Gold (x500)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":500}},{"id":114,"name":"Reward: Gold (x1000)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":1000}},{"id":201,"name":"Reward: Gold (x1500)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":1500}},{"id":190,"name":"Reward: Chest - Golden Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"4","Amount":0}},{"id":74,"name":"Reward: Chest - Mini Event Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"16","Amount":0}},{"id":214,"name":"Reward: Chest - Event Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"39","Amount":0}},{"id":75,"name":"Reward: Chest - Rare Event Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"17","Amount":0}}]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        // LogicLiveEvent #34
        stream.writeVInt(7166)
        stream.writeStringReference('Cup: (2022) Own Line Up 8p')
        stream.writeVInt(4)
        stream.writeVInt(1786795200)
        stream.writeVInt(1786967100)
        stream.writeVInt(1786708800)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Cup: (2022) Own Line Up 8p')
        stream.writeString('{"Color":"#ae2d13","CupLookup":"373","lookupValues":[{"id":373,"name":"Cup -  (2022) Own Lineup - 8P - FrozenValley - EventChest","lookup":"cup_event_lookup","parameters":{"JoinCost":10,"FreeEntriesCount":0,"PlayerCount":8,"GameModeConfig":{"GoaliesDisabled":false,"BallDensity":100,"BallScale":100,"NumberOfBallsOnOvertime":2,"DisableDeckRandomization":false,"ManaGeneration":100,"Arena":10,"NumberOfBalls":1},"BallType":"1","IntermediateRewards":["9","12"],"EndRewards":["190","74"],"FinalReward":"214","NameKey":"survival-generic1-name","DescriptionKey":"survival-generic4-desc"}},{"id":1,"name":"Ball: Normal","lookup":"ball_lookup","parameters":{"Type":"ball"}},{"id":9,"name":"Reward: Gold (x250)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":250}},{"id":12,"name":"Reward: Gold (x750)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":750}},{"id":190,"name":"Reward: Chest - Golden Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"4","Amount":0}},{"id":74,"name":"Reward: Chest - Mini Event Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"16","Amount":0}},{"id":214,"name":"Reward: Chest - Event Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"39","Amount":0}}]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        // LogicLiveEvent #35
        stream.writeVInt(7167)
        stream.writeStringReference('Cup: (2022) Own Line Up 32p')
        stream.writeVInt(4)
        stream.writeVInt(1787227200)
        stream.writeVInt(1787399100)
        stream.writeVInt(1787140800)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Cup: (2022) Own Line Up 32p')
        stream.writeString('{"Color":"#ae2d13","CupLookup":"378","lookupValues":[{"id":378,"name":"Cup - (2022) Own Lineup - 32P - Premier - RareEventChest","lookup":"cup_event_lookup","parameters":{"JoinCost":100,"FreeEntriesCount":0,"PlayerCount":32,"GameModeConfig":{"GoaliesDisabled":false,"BallDensity":100,"BallScale":100,"NumberOfBallsOnOvertime":2,"DisableDeckRandomization":false,"ManaGeneration":100,"Arena":16,"NumberOfBalls":1},"BallType":"1","IntermediateRewards":["194","195","379","380"],"EndRewards":["190","74","214","75"],"FinalReward":"76","NameKey":"survival-generic1-name","DescriptionKey":"survival-generic4-desc"}},{"id":1,"name":"Ball: Normal","lookup":"ball_lookup","parameters":{"Type":"ball"}},{"id":194,"name":"Reward: Gold (x4000)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":4000}},{"id":195,"name":"Reward: Gold (x5000)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":5000}},{"id":379,"name":"Reward: Gold (x6000)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":6000}},{"id":380,"name":"Reward: Gold (x7000)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":7000}},{"id":190,"name":"Reward: Chest - Golden Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"4","Amount":0}},{"id":74,"name":"Reward: Chest - Mini Event Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"16","Amount":0}},{"id":214,"name":"Reward: Chest - Event Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"39","Amount":0}},{"id":75,"name":"Reward: Chest - Rare Event Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"17","Amount":0}},{"id":76,"name":"Reward: Chest - Epic Event Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"18","Amount":0}}]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        // LogicLiveEvent #36
        stream.writeVInt(7169)
        stream.writeStringReference('Gift: Weekend Gift (Gems x100)')
        stream.writeVInt(9)
        stream.writeVInt(1787400000)
        stream.writeVInt(1787485500)
        stream.writeVInt(1787400000)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Gift: Weekend Gift (Gems x100)')
        stream.writeString('{"Color":"#ae2d13","Title":"chronos-gift-gems-description-2","Description":"chronos-gift-gems-description","DonationReward":"115","lookupValues":[{"id":115,"name":"Reward: Gems (x100)","lookup":"reward_lookup","parameters":{"Type":"Gems","RefId":"-1","Amount":100}}]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        // LogicLiveEvent #37
        stream.writeVInt(7171)
        stream.writeStringReference('Kickoff Pass')
        stream.writeVInt(5)
        stream.writeVInt(1786960800)
        stream.writeVInt(1789380000)
        stream.writeVInt(1786960800)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Kickoff Pass')
        stream.writeString('{"Color":"#ae2d13","BattlepassEventMode":"0","BattlepassShopItemId":"70001","lookupValues":[]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        // LogicLiveEvent #38
        stream.writeVInt(7173)
        stream.writeStringReference('Survival - Boom Rocket Madness - 10W3L - Greenfield - EventChest')
        stream.writeVInt(1)
        stream.writeVInt(1787486400)
        stream.writeVInt(1787571900)
        stream.writeVInt(1787400000)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Survival - Boom Rocket Madness - 10W3L - Greenfield - EventChest')
        stream.writeString('{"Color":"#ae2d13","SurvivalLookup":"154","2v2":false,"lookupValues":[{"id":154,"name":"Survival - Boom Rocket Madness - 10W3L - Greenfield - EventChest","lookup":"survival_event_lookup","parameters":{"JoinCost":20,"FreePass":1,"MaxWins":10,"MaxLoss":3,"ManaGeneration":200,"BallDensity":100,"BallScale":100,"NumberOfBalls":3,"NumberOfBallsOnOvertime":4,"ResetWinsOnRetry":false,"NameKey":"survival-rocket-name","DescriptionKey":"survival-rocket-desc-2","Arena":1,"GoaliesDisabled":true,"DisableDeckRandomization":true,"BallType":"1","EndRewardChest":"214","Deck":["18","18","18","18"],"IntermediateRewards":["59","6","189","236","189","173","237","11","190"],"AllowPlayingAfterWin":false}},{"id":1,"name":"Ball: Normal","lookup":"ball_lookup","parameters":{"Type":"ball"}},{"id":214,"name":"Reward: Chest - Event Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"39","Amount":0}},{"id":18,"name":"Spell: Boom Rocket","lookup":"spell_lookup","parameters":{"RefId":"rocket"}},{"id":18,"name":"Spell: Boom Rocket","lookup":"spell_lookup","parameters":{"RefId":"rocket"}},{"id":18,"name":"Spell: Boom Rocket","lookup":"spell_lookup","parameters":{"RefId":"rocket"}},{"id":18,"name":"Spell: Boom Rocket","lookup":"spell_lookup","parameters":{"RefId":"rocket"}},{"id":59,"name":"Reward: Spell - Random Core (x5)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"0","Amount":5}},{"id":6,"name":"Reward: Gold (x100)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":100}},{"id":189,"name":"Reward: Chest - Silver Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"3","Amount":0}},{"id":236,"name":"Reward: Spell - Random Pro (x4)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"1","Amount":4}},{"id":189,"name":"Reward: Chest - Silver Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"3","Amount":0}},{"id":173,"name":"Reward: Gold (x300)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":300}},{"id":237,"name":"Reward: Spell - Random Core (x40)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"0","Amount":40}},{"id":11,"name":"Reward: Gold (x500)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":500}},{"id":190,"name":"Reward: Chest - Golden Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"4","Amount":0}}]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        // LogicLiveEvent #39
        stream.writeVInt(7174)
        stream.writeStringReference('Survival - BeachBall Showdown - 10W3L - RoyalGarden - EventChest')
        stream.writeVInt(1)
        stream.writeVInt(1787659200)
        stream.writeVInt(1787744700)
        stream.writeVInt(1787572800)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Survival - BeachBall Showdown - 10W3L - RoyalGarden - EventChest')
        stream.writeString('{"Color":"#ae2d13","SurvivalLookup":"140","2v2":false,"lookupValues":[{"id":140,"name":"Survival - BeachBall Showdown - 10W3L - RoyalGarden - EventChest","lookup":"survival_event_lookup","parameters":{"JoinCost":20,"FreePass":1,"MaxWins":10,"MaxLoss":3,"ManaGeneration":100,"BallDensity":100,"BallScale":100,"NumberOfBalls":1,"NumberOfBallsOnOvertime":2,"ResetWinsOnRetry":false,"BallType":"2","EndRewardChest":"214","NameKey":"survival-beachball-showdown-name","DescriptionKey":"survival-generic4-desc","Arena":16,"IntermediateRewards":["59","6","189","236","189","173","237","11","190"],"GoaliesDisabled":false,"AllowPlayingAfterWin":false,"DisableDeckRandomization":false}},{"id":2,"name":"Ball: Beach ball","lookup":"ball_lookup","parameters":{"Type":"beachball"}},{"id":214,"name":"Reward: Chest - Event Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"39","Amount":0}},{"id":59,"name":"Reward: Spell - Random Core (x5)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"0","Amount":5}},{"id":6,"name":"Reward: Gold (x100)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":100}},{"id":189,"name":"Reward: Chest - Silver Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"3","Amount":0}},{"id":236,"name":"Reward: Spell - Random Pro (x4)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"1","Amount":4}},{"id":189,"name":"Reward: Chest - Silver Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"3","Amount":0}},{"id":173,"name":"Reward: Gold (x300)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":300}},{"id":237,"name":"Reward: Spell - Random Core (x40)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"0","Amount":40}},{"id":11,"name":"Reward: Gold (x500)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":500}},{"id":190,"name":"Reward: Chest - Golden Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"4","Amount":0}}]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        // LogicLiveEvent #40
        stream.writeVInt(7177)
        stream.writeStringReference('Survival: (2022) Animal Instincts')
        stream.writeVInt(1)
        stream.writeVInt(1787572800)
        stream.writeVInt(1787658300)
        stream.writeVInt(1787486400)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Survival: (2022) Animal Instincts')
        stream.writeString('{"Color":"#ae2d13","SurvivalLookup":"397","2v2":false,"lookupValues":[{"id":397,"name":"Survival - (2022) Animal Instincts - 10W3L - Greenfield - EventChest","lookup":"survival_event_lookup","parameters":{"JoinCost":20,"FreePass":1,"MaxWins":10,"MaxLoss":3,"ManaGeneration":100,"BallDensity":100,"BallScale":100,"NumberOfBalls":2,"NumberOfBallsOnOvertime":3,"ResetWinsOnRetry":false,"NameKey":"survival-chihuahua-name-2","DescriptionKey":"survival-chihuahua-desc","Arena":1,"BallType":"1","EndRewardChest":"214","Deck":["396","55","155","43","198","339","46","45"],"IntermediateRewards":["59","6","189","236","189","173","237","11","190"],"GoaliesDisabled":false,"AllowPlayingAfterWin":false,"DisableDeckRandomization":false}},{"id":1,"name":"Ball: Normal","lookup":"ball_lookup","parameters":{"Type":"ball"}},{"id":214,"name":"Reward: Chest - Event Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"39","Amount":0}},{"id":396,"name":"Spell: Chihuahua","lookup":"spell_lookup","parameters":{"RefId":"chihuahua"}},{"id":55,"name":"Spell: Tiny Tanuki","lookup":"spell_lookup","parameters":{"RefId":"tanuki"}},{"id":155,"name":"Spell: Camper Koala","lookup":"spell_lookup","parameters":{"RefId":"koala"}},{"id":43,"name":"Spell: Melon","lookup":"spell_lookup","parameters":{"RefId":"melon"}},{"id":198,"name":"Spell: Blast Sheep","lookup":"spell_lookup","parameters":{"RefId":"sheep"}},{"id":339,"name":"Spell: Explosive Chick","lookup":"spell_lookup","parameters":{"RefId":"bigchick"}},{"id":46,"name":"Spell: Mr. Mine","lookup":"spell_lookup","parameters":{"RefId":"mine"}},{"id":45,"name":"Spell: Mr. Fire","lookup":"spell_lookup","parameters":{"RefId":"explosive"}},{"id":59,"name":"Reward: Spell - Random Core (x5)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"0","Amount":5}},{"id":6,"name":"Reward: Gold (x100)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":100}},{"id":189,"name":"Reward: Chest - Silver Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"3","Amount":0}},{"id":236,"name":"Reward: Spell - Random Pro (x4)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"1","Amount":4}},{"id":189,"name":"Reward: Chest - Silver Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"3","Amount":0}},{"id":173,"name":"Reward: Gold (x300)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":300}},{"id":237,"name":"Reward: Spell - Random Core (x40)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"0","Amount":40}},{"id":11,"name":"Reward: Gold (x500)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":500}},{"id":190,"name":"Reward: Chest - Golden Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"4","Amount":0}}]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        // LogicLiveEvent #41
        stream.writeVInt(7178)
        stream.writeStringReference('Survival - Panda Special Challenge - 8W3L - Greenfield - EventChest/Panda')
        stream.writeVInt(1)
        stream.writeVInt(1787745600)
        stream.writeVInt(1787831100)
        stream.writeVInt(1787659200)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Survival - Panda Special Challenge - 8W3L - Greenfield - EventChest/Panda')
        stream.writeString('{"Color":"#ae2d13","SurvivalLookup":"183","2v2":false,"lookupValues":[{"id":183,"name":"Survival - Special Challenge Lazy Panda - 8W3L - Greenfield - EventChest/Panda","lookup":"survival_event_lookup","parameters":{"JoinCost":20,"FreePass":1,"MaxWins":8,"MaxLoss":3,"ManaGeneration":150,"BallDensity":100,"BallScale":100,"NumberOfBalls":1,"NumberOfBallsOnOvertime":2,"ResetWinsOnRetry":false,"NameKey":"survival-specialchallenge-pawn-name","DescriptionKey":"survival-pawn-desc","Arena":0,"GoaliesDisabled":false,"DisableDeckRandomization":false,"BallType":"1","EndRewardChest":"214","Deck":["36","35","28","52","56","45","43","40"],"IntermediateRewards":["170","60","189","8","204","189","203"],"AllowPlayingAfterWin":false,"EndRewardSpecificSpell":"97"}},{"id":1,"name":"Ball: Normal","lookup":"ball_lookup","parameters":{"Type":"ball"}},{"id":214,"name":"Reward: Chest - Event Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"39","Amount":0}},{"id":36,"name":"Spell: Lazy Panda","lookup":"spell_lookup","parameters":{"RefId":"pawn"}},{"id":35,"name":"Spell: Ice Boy","lookup":"spell_lookup","parameters":{"RefId":"freeze"}},{"id":28,"name":"Spell: Fan","lookup":"spell_lookup","parameters":{"RefId":"fan"}},{"id":52,"name":"Spell: Sticky Puffer","lookup":"spell_lookup","parameters":{"RefId":"puffer"}},{"id":56,"name":"Spell: Turtle Spinner","lookup":"spell_lookup","parameters":{"RefId":"turtle"}},{"id":45,"name":"Spell: Mr. Fire","lookup":"spell_lookup","parameters":{"RefId":"explosive"}},{"id":43,"name":"Spell: Melon","lookup":"spell_lookup","parameters":{"RefId":"melon"}},{"id":40,"name":"Spell: Loyal Dog","lookup":"spell_lookup","parameters":{"RefId":"support"}},{"id":170,"name":"Reward: Gold (x40)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":40}},{"id":60,"name":"Reward: Spell - Random Core (x10)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"0","Amount":10}},{"id":189,"name":"Reward: Chest - Silver Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"3","Amount":0}},{"id":8,"name":"Reward: Gold (x200)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":200}},{"id":204,"name":"Reward: Spell - Random Pro (x5)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"1","Amount":5}},{"id":189,"name":"Reward: Chest - Silver Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"3","Amount":0}},{"id":203,"name":"Reward: Gold (x400)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":400}},{"id":97,"name":"Reward: Spell - Panda (x25)","lookup":"reward_lookup","parameters":{"Type":"SpellSpecific","RefId":"pawn","Amount":25}}]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

    }
}