export class LogicLiveEvent {
    static COUNT = 42

    static encode(stream) { 
        stream.writeVInt(6831)
        stream.writeStringReference('Offer: Hero Chest C - 7 - "football-9"')
        stream.writeVInt(0)
        stream.writeVInt(1780100100)
        stream.writeVInt(1780271940)
        stream.writeVInt(1780100100)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Offer: Hero Chest C - 7 - "football-9"')
        stream.writeString('{"Color":"#448932","ShopSpenderDaysInActive":7,"ShopSpenderPercentageIncrease":50,"ShopSpenderCapWeekly":true,"ShopSpenderCapMonthly":true,"ShopSpenderCapAllTime":true,"OverrideName":"chronos-special-offer-football-9","TierDefaultShopItem":"7016007","Tier1ShopItem":"7016007","Tier2ShopItem":"7016007","Tier3ShopItem":"7016007","Tier4ShopItem":"7016007","Tier5ShopItem":"7016007","Tier6ShopItem":"7016007","Tier7ShopItem":"7016007","Tier8ShopItem":"7016007","Tier9ShopItem":"7016007","Tier10ShopItem":"7016010","Tier15ShopItem":"7016015","Tier20ShopItem":"7016020","Tier50ShopItem":"7016050","Tier60ShopItem":"7016060","lookupValues":[]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        stream.writeVInt(6839)
        stream.writeStringReference('Offer - Stock up on Gold - Goldrush-2 (NOBLE A) ')
        stream.writeVInt(0)
        stream.writeVInt(1779927300)
        stream.writeVInt(1780099140)
        stream.writeVInt(1779927300)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Offer - Stock up on Gold - Goldrush-2 (NOBLE A) ')
        stream.writeString('{"Color":"#448932","ShopSpenderDaysInActive":7,"ShopSpenderPercentageIncrease":50,"ShopSpenderCapWeekly":true,"ShopSpenderCapMonthly":true,"ShopSpenderCapAllTime":true,"TierDefaultShopItem":"7019005","Tier1ShopItem":"7001001","Tier2ShopItem":"7019002","Tier3ShopItem":"7019003","Tier4ShopItem":"7019003","Tier5ShopItem":"7019005","Tier6ShopItem":"7019005","Tier7ShopItem":"7019007","Tier8ShopItem":"7019007","Tier9ShopItem":"7019007","Tier10ShopItem":"7019010","Tier15ShopItem":"7019015","Tier20ShopItem":"7019020","Tier50ShopItem":"7019050","Tier60ShopItem":"7019060","OverrideName":"chronos-special-offer-goldrush-2","lookupValues":[]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        stream.writeVInt(6845)
        stream.writeStringReference('Survival - Boom Rocket Madness - 10W3L - Greenfield - EventChest')
        stream.writeVInt(1)
        stream.writeVInt(1780228800)
        stream.writeVInt(1780314300)
        stream.writeVInt(1780142400)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Survival - Boom Rocket Madness - 10W3L - Greenfield - EventChest')
        stream.writeString('{"Color":"#ae2d13","SurvivalLookup":"154","2v2":false,"lookupValues":[{"id":154,"name":"Survival - Boom Rocket Madness - 10W3L - Greenfield - EventChest","lookup":"survival_event_lookup","parameters":{"JoinCost":20,"FreePass":1,"MaxWins":10,"MaxLoss":3,"ManaGeneration":200,"BallDensity":100,"BallScale":100,"NumberOfBalls":3,"NumberOfBallsOnOvertime":4,"ResetWinsOnRetry":false,"NameKey":"survival-rocket-name","DescriptionKey":"survival-rocket-desc-2","Arena":1,"GoaliesDisabled":true,"DisableDeckRandomization":true,"BallType":"1","EndRewardChest":"214","Deck":["18","18","18","18"],"IntermediateRewards":["59","6","189","236","189","173","237","11","190"],"AllowPlayingAfterWin":false}},{"id":1,"name":"Ball: Normal","lookup":"ball_lookup","parameters":{"Type":"ball"}},{"id":214,"name":"Reward: Chest - Event Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"39","Amount":0}},{"id":18,"name":"Spell: Boom Rocket","lookup":"spell_lookup","parameters":{"RefId":"rocket"}},{"id":18,"name":"Spell: Boom Rocket","lookup":"spell_lookup","parameters":{"RefId":"rocket"}},{"id":18,"name":"Spell: Boom Rocket","lookup":"spell_lookup","parameters":{"RefId":"rocket"}},{"id":18,"name":"Spell: Boom Rocket","lookup":"spell_lookup","parameters":{"RefId":"rocket"}},{"id":59,"name":"Reward: Spell - Random Core (x5)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"0","Amount":5}},{"id":6,"name":"Reward: Gold (x100)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":100}},{"id":189,"name":"Reward: Chest - Silver Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"3","Amount":0}},{"id":236,"name":"Reward: Spell - Random Pro (x4)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"1","Amount":4}},{"id":189,"name":"Reward: Chest - Silver Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"3","Amount":0}},{"id":173,"name":"Reward: Gold (x300)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":300}},{"id":237,"name":"Reward: Spell - Random Core (x40)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"0","Amount":40}},{"id":11,"name":"Reward: Gold (x500)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":500}},{"id":190,"name":"Reward: Chest - Golden Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"4","Amount":0}}]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        stream.writeVInt(6866)
        stream.writeStringReference('2v2 - Triple Energy Rush - 20W - El Dorado - Event Chest')
        stream.writeVInt(2)
        stream.writeVInt(1780228800)
        stream.writeVInt(1780314300)
        stream.writeVInt(1780142400)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('2v2 - Triple Energy Rush - 20W - El Dorado - Event Chest')
        stream.writeString('{"Color":"#ae2d13","2V2Lookup":"293","lookupValues":[{"id":293,"name":"2v2 - Triple Energy Rush - 20W - El Dorado - Event Chest","lookup":"2v2_event_lookup","parameters":{"NameKey":"survival-triple-energy-rush-name","DescriptionKey":"survival-triple-energy-rush-desc","GameModeConfig":{"GoaliesDisabled":false,"BallDensity":100,"BallScale":100,"NumberOfBallsOnOvertime":2,"DisableDeckRandomization":false,"ManaGeneration":300,"Arena":4,"NumberOfBalls":1},"BallType":"1","IntermediateRewards":["59","6","189","236","189","173","237","11","190","214"],"WinsRequired":[2,4,6,8,10,12,14,16,18,20]}},{"id":1,"name":"Ball: Normal","lookup":"ball_lookup","parameters":{"Type":"ball"}},{"id":59,"name":"Reward: Spell - Random Core (x5)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"0","Amount":5}},{"id":6,"name":"Reward: Gold (x100)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":100}},{"id":189,"name":"Reward: Chest - Silver Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"3","Amount":0}},{"id":236,"name":"Reward: Spell - Random Pro (x4)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"1","Amount":4}},{"id":189,"name":"Reward: Chest - Silver Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"3","Amount":0}},{"id":173,"name":"Reward: Gold (x300)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":300}},{"id":237,"name":"Reward: Spell - Random Core (x40)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"0","Amount":40}},{"id":11,"name":"Reward: Gold (x500)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":500}},{"id":190,"name":"Reward: Chest - Golden Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"4","Amount":0}},{"id":214,"name":"Reward: Chest - Event Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"39","Amount":0}}]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        stream.writeVInt(6873)
        stream.writeStringReference('2v2 - No Goalie - 20W - ZenPalace - EpicChest')
        stream.writeVInt(2)
        stream.writeVInt(1780056000)
        stream.writeVInt(1780227900)
        stream.writeVInt(1779969600)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('2v2 - No Goalie - 20W - ZenPalace - EpicChest')
        stream.writeString('{"Color":"#ae2d13","2V2Lookup":"258","lookupValues":[{"id":258,"name":"2v2 - No Goalie - 20W - ZenPalace - EpicChest","lookup":"2v2_event_lookup","parameters":{"NameKey":"survival-no-goalie-name","DescriptionKey":"survival-no-goalie-desc","GameModeConfig":{"GoaliesDisabled":true,"BallDensity":100,"BallScale":100,"NumberOfBallsOnOvertime":2,"DisableDeckRandomization":false,"ManaGeneration":100,"Arena":7,"NumberOfBalls":1},"BallType":"1","IntermediateRewards":["236","189","173","237","190","238","228","190","150","76"],"WinsRequired":[2,4,6,8,10,12,14,16,18,20]}},{"id":1,"name":"Ball: Normal","lookup":"ball_lookup","parameters":{"Type":"ball"}},{"id":236,"name":"Reward: Spell - Random Pro (x4)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"1","Amount":4}},{"id":189,"name":"Reward: Chest - Silver Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"3","Amount":0}},{"id":173,"name":"Reward: Gold (x300)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":300}},{"id":237,"name":"Reward: Spell - Random Core (x40)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"0","Amount":40}},{"id":190,"name":"Reward: Chest - Golden Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"4","Amount":0}},{"id":238,"name":"Reward: Gold (x600)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":600}},{"id":228,"name":"Reward: Spell - Random Pro (x16)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"1","Amount":16}},{"id":190,"name":"Reward: Chest - Golden Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"4","Amount":0}},{"id":150,"name":"Reward: Spell - Random Superstar (x1)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"2","Amount":1}},{"id":76,"name":"Reward: Chest - Epic Event Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"18","Amount":0}}]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        stream.writeVInt(6897)
        stream.writeStringReference('Survival - Special Challenge Froggy - 12W3L - Greenfield - EpicChest/Froggy')
        stream.writeVInt(1)
        stream.writeVInt(1780056000)
        stream.writeVInt(1780227900)
        stream.writeVInt(1779969600)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Survival - Special Challenge Froggy - 12W3L - Greenfield - EpicChest/Froggy')
        stream.writeString('{"Color":"#ae2d13","SurvivalLookup":"182","2v2":false,"lookupValues":[{"id":182,"name":"Survival - Special Challenge Froggy - 12W3L - Greenfield - EpicChest/Froggy","lookup":"survival_event_lookup","parameters":{"JoinCost":50,"FreePass":1,"MaxWins":12,"MaxLoss":3,"ManaGeneration":150,"BallDensity":100,"BallScale":100,"NumberOfBalls":1,"NumberOfBallsOnOvertime":2,"ResetWinsOnRetry":false,"NameKey":"survival-specialchallenge-frog-name","DescriptionKey":"survival-frog-desc","Arena":1,"GoaliesDisabled":false,"DisableDeckRandomization":false,"BallType":"1","EndRewardChest":"76","Deck":["31","41","44","47","36","54","40","43"],"IntermediateRewards":["60","8","189","67","189","114","190","210","192","150","72"],"AllowPlayingAfterWin":false,"EndRewardSpecificSpell":"156"}},{"id":1,"name":"Ball: Normal","lookup":"ball_lookup","parameters":{"Type":"ball"}},{"id":76,"name":"Reward: Chest - Epic Event Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"18","Amount":0}},{"id":31,"name":"Spell: Froggy","lookup":"spell_lookup","parameters":{"RefId":"frog"}},{"id":41,"name":"Spell: Magnetman","lookup":"spell_lookup","parameters":{"RefId":"magnet"}},{"id":44,"name":"Spell: Mr. Bigshot","lookup":"spell_lookup","parameters":{"RefId":"shotgun"}},{"id":47,"name":"Spell: Raging Bull","lookup":"spell_lookup","parameters":{"RefId":"bull"}},{"id":36,"name":"Spell: Lazy Panda","lookup":"spell_lookup","parameters":{"RefId":"pawn"}},{"id":54,"name":"Spell: Striker Tiger","lookup":"spell_lookup","parameters":{"RefId":"attacker"}},{"id":40,"name":"Spell: Loyal Dog","lookup":"spell_lookup","parameters":{"RefId":"support"}},{"id":43,"name":"Spell: Melon","lookup":"spell_lookup","parameters":{"RefId":"melon"}},{"id":60,"name":"Reward: Spell - Random Core (x10)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"0","Amount":10}},{"id":8,"name":"Reward: Gold (x200)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":200}},{"id":189,"name":"Reward: Chest - Silver Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"3","Amount":0}},{"id":67,"name":"Reward: Spell - Random Pro (x12)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"1","Amount":12}},{"id":189,"name":"Reward: Chest - Silver Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"3","Amount":0}},{"id":114,"name":"Reward: Gold (x1000)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":1000}},{"id":190,"name":"Reward: Chest - Golden Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"4","Amount":0}},{"id":210,"name":"Reward: Spell - Random Core (x125)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"0","Amount":125}},{"id":192,"name":"Reward: Gold (x2000)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":2000}},{"id":150,"name":"Reward: Spell - Random Superstar (x1)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"2","Amount":1}},{"id":72,"name":"Reward: Chest - Colossal Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"5","Amount":0}},{"id":156,"name":"Reward: Spell - Froggy (x5)","lookup":"reward_lookup","parameters":{"Type":"SpellSpecific","RefId":"frog","Amount":5}}]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        stream.writeVInt(6899)
        stream.writeStringReference('Gift: Weekend Gift (Gems x100)')
        stream.writeVInt(9)
        stream.writeVInt(1780142400)
        stream.writeVInt(1780227900)
        stream.writeVInt(1780142400)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Gift: Weekend Gift (Gems x100)')
        stream.writeString('{"Color":"#ae2d13","Title":"chronos-gift-gems-description-2","Description":"chronos-gift-gems-description","DonationReward":"115","lookupValues":[{"id":115,"name":"Reward: Gems (x100)","lookup":"reward_lookup","parameters":{"Type":"Gems","RefId":"-1","Amount":100}}]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        stream.writeVInt(6901)
        stream.writeStringReference('Cup - (2022) Bowling Showdown - 8P')
        stream.writeVInt(4)
        stream.writeVInt(1780142400)
        stream.writeVInt(1780314300)
        stream.writeVInt(1780056000)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Cup - (2022) Bowling Showdown - 8P')
        stream.writeString('{"Color":"#ae2d13","CupLookup":"384","lookupValues":[{"id":384,"name":"Cup - (2022) Bowling Showdown - 8P - El Dorado - Mini Event Chest","lookup":"cup_event_lookup","parameters":{"JoinCost":10,"FreeEntriesCount":0,"PlayerCount":8,"GameModeConfig":{"GoaliesDisabled":false,"BallDensity":100,"BallScale":100,"NumberOfBallsOnOvertime":2,"DisableDeckRandomization":false,"ManaGeneration":100,"Arena":4,"NumberOfBalls":1},"BallType":"3","IntermediateRewards":["9","12"],"EndRewards":["190","74"],"FinalReward":"214","NameKey":"survival-bowling-showdown-name","DescriptionKey":"survival-rumble-showdown-desc"}},{"id":3,"name":"Ball: Bowling ball","lookup":"ball_lookup","parameters":{"Type":"bowlingball"}},{"id":9,"name":"Reward: Gold (x250)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":250}},{"id":12,"name":"Reward: Gold (x750)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":750}},{"id":190,"name":"Reward: Chest - Golden Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"4","Amount":0}},{"id":74,"name":"Reward: Chest - Mini Event Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"16","Amount":0}},{"id":214,"name":"Reward: Chest - Event Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"39","Amount":0}}]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        stream.writeVInt(6904)
        stream.writeStringReference('Cup: (2022) Own Line Up 32p')
        stream.writeVInt(4)
        stream.writeVInt(1779969600)
        stream.writeVInt(1780141500)
        stream.writeVInt(1779883200)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Cup: (2022) Own Line Up 32p')
        stream.writeString('{"Color":"#ae2d13","CupLookup":"378","lookupValues":[{"id":378,"name":"Cup - (2022) Own Lineup - 32P - Premier - RareEventChest","lookup":"cup_event_lookup","parameters":{"JoinCost":100,"FreeEntriesCount":0,"PlayerCount":32,"GameModeConfig":{"GoaliesDisabled":false,"BallDensity":100,"BallScale":100,"NumberOfBallsOnOvertime":2,"DisableDeckRandomization":false,"ManaGeneration":100,"Arena":16,"NumberOfBalls":1},"BallType":"1","IntermediateRewards":["194","195","379","380"],"EndRewards":["190","74","214","75"],"FinalReward":"76","NameKey":"survival-generic1-name","DescriptionKey":"survival-generic4-desc"}},{"id":1,"name":"Ball: Normal","lookup":"ball_lookup","parameters":{"Type":"ball"}},{"id":194,"name":"Reward: Gold (x4000)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":4000}},{"id":195,"name":"Reward: Gold (x5000)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":5000}},{"id":379,"name":"Reward: Gold (x6000)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":6000}},{"id":380,"name":"Reward: Gold (x7000)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":7000}},{"id":190,"name":"Reward: Chest - Golden Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"4","Amount":0}},{"id":74,"name":"Reward: Chest - Mini Event Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"16","Amount":0}},{"id":214,"name":"Reward: Chest - Event Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"39","Amount":0}},{"id":75,"name":"Reward: Chest - Rare Event Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"17","Amount":0}},{"id":76,"name":"Reward: Chest - Epic Event Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"18","Amount":0}}]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        stream.writeVInt(6905)
        stream.writeStringReference('Survival - Special Challenge Dashing Deer - 10W3L - Frozen Valley - RareChest/Deer')
        stream.writeVInt(1)
        stream.writeVInt(1780315200)
        stream.writeVInt(1780400700)
        stream.writeVInt(1780228800)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Survival - Special Challenge Dashing Deer - 10W3L - Frozen Valley - RareChest/Deer')
        stream.writeString('{"Color":"#ae2d13","SurvivalLookup":"248","2v2":false,"lookupValues":[{"id":248,"name":"Survival - Special Challenge Dashing Deer - 10W3L - Frozen Valley - RareChest/Deer","lookup":"survival_event_lookup","parameters":{"JoinCost":30,"FreePass":1,"MaxWins":10,"MaxLoss":3,"ManaGeneration":150,"BallDensity":100,"BallScale":100,"NumberOfBalls":1,"NumberOfBallsOnOvertime":2,"ResetWinsOnRetry":false,"NameKey":"survival-specialchallenge-deer-name","DescriptionKey":"survival-deer-desc","Arena":1,"GoaliesDisabled":false,"DisableDeckRandomization":false,"BallType":"1","EndRewardChest":"75","Deck":["24","27","31","41","43","155","16","36"],"IntermediateRewards":["189","7","212","189","205","189","190","211","150"],"AllowPlayingAfterWin":false,"EndRewardSpecificSpell":"243"}},{"id":1,"name":"Ball: Normal","lookup":"ball_lookup","parameters":{"Type":"ball"}},{"id":75,"name":"Reward: Chest - Rare Event Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"17","Amount":0}},{"id":24,"name":"Spell: Dashing Deer","lookup":"spell_lookup","parameters":{"RefId":"reindeer"}},{"id":27,"name":"Spell: Fake Ball","lookup":"spell_lookup","parameters":{"RefId":"decoy"}},{"id":31,"name":"Spell: Froggy","lookup":"spell_lookup","parameters":{"RefId":"frog"}},{"id":41,"name":"Spell: Magnetman","lookup":"spell_lookup","parameters":{"RefId":"magnet"}},{"id":43,"name":"Spell: Melon","lookup":"spell_lookup","parameters":{"RefId":"melon"}},{"id":155,"name":"Spell: Camper Koala","lookup":"spell_lookup","parameters":{"RefId":"koala"}},{"id":16,"name":"Spell: Bomba","lookup":"spell_lookup","parameters":{"RefId":"bomb"}},{"id":36,"name":"Spell: Lazy Panda","lookup":"spell_lookup","parameters":{"RefId":"pawn"}},{"id":189,"name":"Reward: Chest - Silver Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"3","Amount":0}},{"id":7,"name":"Reward: Gold (x150)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":150}},{"id":212,"name":"Reward: Spell - Random Core (x25)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"0","Amount":25}},{"id":189,"name":"Reward: Chest - Silver Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"3","Amount":0}},{"id":205,"name":"Reward: Spell - Random Pro (x8)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"1","Amount":8}},{"id":189,"name":"Reward: Chest - Silver Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"3","Amount":0}},{"id":190,"name":"Reward: Chest - Golden Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"4","Amount":0}},{"id":211,"name":"Reward: Spell - Random Core (x75)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"0","Amount":75}},{"id":150,"name":"Reward: Spell - Random Superstar (x1)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"2","Amount":1}},{"id":243,"name":"Reward: Spell - Dashing Deer (x10)","lookup":"reward_lookup","parameters":{"Type":"SpellSpecific","RefId":"reindeer","Amount":10}}]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        stream.writeVInt(6906)
        stream.writeStringReference('Survival - Special Challenge Heavy Rat - 8W3L - Zen Palace - EventChest/Rat')
        stream.writeVInt(1)
        stream.writeVInt(1780488000)
        stream.writeVInt(1780573500)
        stream.writeVInt(1780401600)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Survival - Special Challenge Heavy Rat - 8W3L - Zen Palace - EventChest/Rat')
        stream.writeString('{"Color":"#ae2d13","SurvivalLookup":"328","2v2":false,"lookupValues":[{"id":328,"name":"Survival - Special Challenge Heavy Rat - 8W3L - Zen Palace - EventChest/Rat","lookup":"survival_event_lookup","parameters":{"JoinCost":20,"FreePass":1,"MaxWins":8,"MaxLoss":3,"ManaGeneration":150,"BallDensity":100,"BallScale":100,"NumberOfBalls":1,"NumberOfBallsOnOvertime":2,"ResetWinsOnRetry":false,"NameKey":"survival-specialchallenge-rat-name","DescriptionKey":"survival-rat-desc","Arena":7,"BallType":"1","EndRewardChest":"214","EndRewardSpecificSpell":"326","Deck":["323","22","253","39","43","56","49","35"],"IntermediateRewards":["170","60","189","8","204","189","203"],"GoaliesDisabled":false,"AllowPlayingAfterWin":false,"DisableDeckRandomization":false}},{"id":1,"name":"Ball: Normal","lookup":"ball_lookup","parameters":{"Type":"ball"}},{"id":214,"name":"Reward: Chest - Event Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"39","Amount":0}},{"id":326,"name":"Reward: Spell - Rat (x25)","lookup":"reward_lookup","parameters":{"Type":"SpellSpecific","RefId":"rat","Amount":25}},{"id":323,"name":"Spell: Heavy Rat","lookup":"spell_lookup","parameters":{"RefId":"rat"}},{"id":22,"name":"Spell: Crazy Cat","lookup":"spell_lookup","parameters":{"RefId":"cat"}},{"id":253,"name":"Spell: Spy Chameleon","lookup":"spell_lookup","parameters":{"RefId":"chameleon"}},{"id":39,"name":"Spell: Lover","lookup":"spell_lookup","parameters":{"RefId":"lover"}},{"id":43,"name":"Spell: Melon","lookup":"spell_lookup","parameters":{"RefId":"melon"}},{"id":56,"name":"Spell: Turtle Spinner","lookup":"spell_lookup","parameters":{"RefId":"turtle"}},{"id":49,"name":"Spell: Royal Dung","lookup":"spell_lookup","parameters":{"RefId":"dung"}},{"id":35,"name":"Spell: Ice Boy","lookup":"spell_lookup","parameters":{"RefId":"freeze"}},{"id":170,"name":"Reward: Gold (x40)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":40}},{"id":60,"name":"Reward: Spell - Random Core (x10)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"0","Amount":10}},{"id":189,"name":"Reward: Chest - Silver Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"3","Amount":0}},{"id":8,"name":"Reward: Gold (x200)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":200}},{"id":204,"name":"Reward: Spell - Random Pro (x5)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"1","Amount":5}},{"id":189,"name":"Reward: Chest - Silver Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"3","Amount":0}},{"id":203,"name":"Reward: Gold (x400)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":400}}]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        stream.writeVInt(6907)
        stream.writeStringReference('Survival - Winstreak Challenge Unicorn - 10W3L - Greenfield - LegendaryChest')
        stream.writeVInt(1)
        stream.writeVInt(1780660800)
        stream.writeVInt(1780832700)
        stream.writeVInt(1780574400)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Survival - Winstreak Challenge Unicorn - 10W3L - Greenfield - LegendaryChest')
        stream.writeString('{"Color":"#ae2d13","SurvivalLookup":"233","2v2":false,"lookupValues":[{"id":233,"name":"Survival - Winstreak Challenge Unicorn - 10W3L - Greenfield - LegendaryChest","lookup":"survival_event_lookup","parameters":{"JoinCost":30,"FreePass":1,"MaxWins":10,"MaxLoss":1,"ManaGeneration":100,"BallDensity":100,"BallScale":100,"NumberOfBalls":1,"NumberOfBallsOnOvertime":2,"ResetWinsOnRetry":true,"NameKey":"survival-winstreak-name","DescriptionKey":"survival-winstreak-desc","Arena":0,"BallType":"1","EndRewardChest":"137","IntermediateRewards":["11","189","114","190","192","72","195","191","196"],"GoaliesDisabled":false,"AllowPlayingAfterWin":false,"DisableDeckRandomization":false,"EndRewardSpecificSpell":"167"}},{"id":1,"name":"Ball: Normal","lookup":"ball_lookup","parameters":{"Type":"ball"}},{"id":137,"name":"Reward: Chest - Legendary Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"13","Amount":0}},{"id":11,"name":"Reward: Gold (x500)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":500}},{"id":189,"name":"Reward: Chest - Silver Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"3","Amount":0}},{"id":114,"name":"Reward: Gold (x1000)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":1000}},{"id":190,"name":"Reward: Chest - Golden Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"4","Amount":0}},{"id":192,"name":"Reward: Gold (x2000)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":2000}},{"id":72,"name":"Reward: Chest - Colossal Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"5","Amount":0}},{"id":195,"name":"Reward: Gold (x5000)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":5000}},{"id":191,"name":"Reward: Chest - Super Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"6","Amount":0}},{"id":196,"name":"Reward: Gold (x10000)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":10000}},{"id":167,"name":"Reward: Spell - Unicorn (x1)","lookup":"reward_lookup","parameters":{"Type":"SpellSpecific","RefId":"unicorn","Amount":1}}]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        stream.writeVInt(6908)
        stream.writeStringReference('Survival: (2022) Pass Day')
        stream.writeVInt(1)
        stream.writeVInt(1780920000)
        stream.writeVInt(1781005500)
        stream.writeVInt(1780833600)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Survival: (2022) Pass Day')
        stream.writeString('{"Color":"#ae2d13","SurvivalLookup":"388","2v2":false,"lookupValues":[{"id":388,"name":"Survival - (2022) Pass Day - 10W3L - El Dorado - RareChest","lookup":"survival_event_lookup","parameters":{"JoinCost":30,"FreePass":1,"MaxWins":10,"MaxLoss":3,"ManaGeneration":100,"BallDensity":100,"BallScale":100,"NumberOfBalls":1,"NumberOfBallsOnOvertime":2,"ResetWinsOnRetry":false,"NameKey":"survival-pass-day-name","DescriptionKey":"survival-pass-day-desc","Arena":5,"BallType":"1","EndRewardChest":"75","Deck":["342","24","350","39","27","31","155","45"],"IntermediateRewards":["5","65","189","62","189","10","190","228","227"],"GoaliesDisabled":false,"AllowPlayingAfterWin":false,"DisableDeckRandomization":false}},{"id":1,"name":"Ball: Normal","lookup":"ball_lookup","parameters":{"Type":"ball"}},{"id":75,"name":"Reward: Chest - Rare Event Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"17","Amount":0}},{"id":342,"name":"Spell: Skeleton Dinos","lookup":"spell_lookup","parameters":{"RefId":"dino_dead_hockey"}},{"id":24,"name":"Spell: Dashing Deer","lookup":"spell_lookup","parameters":{"RefId":"reindeer"}},{"id":350,"name":"Spell: Dozy Owl","lookup":"spell_lookup","parameters":{"RefId":"owl"}},{"id":39,"name":"Spell: Lover","lookup":"spell_lookup","parameters":{"RefId":"lover"}},{"id":27,"name":"Spell: Fake Ball","lookup":"spell_lookup","parameters":{"RefId":"decoy"}},{"id":31,"name":"Spell: Froggy","lookup":"spell_lookup","parameters":{"RefId":"frog"}},{"id":155,"name":"Spell: Camper Koala","lookup":"spell_lookup","parameters":{"RefId":"koala"}},{"id":45,"name":"Spell: Mr. Fire","lookup":"spell_lookup","parameters":{"RefId":"explosive"}},{"id":5,"name":"Reward: Gold (x75)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":75}},{"id":65,"name":"Reward: Spell - Random Pro (x3)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"1","Amount":3}},{"id":189,"name":"Reward: Chest - Silver Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"3","Amount":0}},{"id":62,"name":"Reward: Spell - Random Core (x30)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"0","Amount":30}},{"id":189,"name":"Reward: Chest - Silver Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"3","Amount":0}},{"id":10,"name":"Reward: Gold (x450)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":450}},{"id":190,"name":"Reward: Chest - Golden Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"4","Amount":0}},{"id":228,"name":"Reward: Spell - Random Pro (x16)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"1","Amount":16}},{"id":227,"name":"Reward: Gold (x900)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":900}}]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        stream.writeVInt(6909)
        stream.writeStringReference('Survival - BeachBall Showdown - 10W3L - RoyalGarden - EventChest')
        stream.writeVInt(1)
        stream.writeVInt(1780401600)
        stream.writeVInt(1780487100)
        stream.writeVInt(1780315200)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Survival - BeachBall Showdown - 10W3L - RoyalGarden - EventChest')
        stream.writeString('{"Color":"#ae2d13","SurvivalLookup":"140","2v2":false,"lookupValues":[{"id":140,"name":"Survival - BeachBall Showdown - 10W3L - RoyalGarden - EventChest","lookup":"survival_event_lookup","parameters":{"JoinCost":20,"FreePass":1,"MaxWins":10,"MaxLoss":3,"ManaGeneration":100,"BallDensity":100,"BallScale":100,"NumberOfBalls":1,"NumberOfBallsOnOvertime":2,"ResetWinsOnRetry":false,"BallType":"2","EndRewardChest":"214","NameKey":"survival-beachball-showdown-name","DescriptionKey":"survival-generic4-desc","Arena":16,"IntermediateRewards":["59","6","189","236","189","173","237","11","190"],"GoaliesDisabled":false,"AllowPlayingAfterWin":false,"DisableDeckRandomization":false}},{"id":2,"name":"Ball: Beach ball","lookup":"ball_lookup","parameters":{"Type":"beachball"}},{"id":214,"name":"Reward: Chest - Event Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"39","Amount":0}},{"id":59,"name":"Reward: Spell - Random Core (x5)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"0","Amount":5}},{"id":6,"name":"Reward: Gold (x100)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":100}},{"id":189,"name":"Reward: Chest - Silver Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"3","Amount":0}},{"id":236,"name":"Reward: Spell - Random Pro (x4)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"1","Amount":4}},{"id":189,"name":"Reward: Chest - Silver Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"3","Amount":0}},{"id":173,"name":"Reward: Gold (x300)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":300}},{"id":237,"name":"Reward: Spell - Random Core (x40)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"0","Amount":40}},{"id":11,"name":"Reward: Gold (x500)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":500}},{"id":190,"name":"Reward: Chest - Golden Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"4","Amount":0}}]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        stream.writeVInt(6910)
        stream.writeStringReference('Survival - Triple Energy Rush - 10W3L - ElDorado - EventChest')
        stream.writeVInt(1)
        stream.writeVInt(1780574400)
        stream.writeVInt(1780659900)
        stream.writeVInt(1780488000)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Survival - Triple Energy Rush - 10W3L - ElDorado - EventChest')
        stream.writeString('{"Color":"#ae2d13","SurvivalLookup":"93","2v2":false,"lookupValues":[{"id":93,"name":"Survival - Triple Energy Rush - 10W3L - El Dorado - EventChest","lookup":"survival_event_lookup","parameters":{"JoinCost":20,"FreePass":1,"MaxWins":10,"MaxLoss":3,"ManaGeneration":300,"BallDensity":100,"BallScale":100,"NumberOfBalls":1,"NumberOfBallsOnOvertime":2,"ResetWinsOnRetry":false,"NameKey":"survival-triple-energy-rush-name","DescriptionKey":"survival-triple-energy-rush-desc","Arena":4,"BallType":"1","EndRewardChest":"214","IntermediateRewards":["59","6","189","236","189","173","237","11","190"],"GoaliesDisabled":false,"AllowPlayingAfterWin":false,"DisableDeckRandomization":false}},{"id":1,"name":"Ball: Normal","lookup":"ball_lookup","parameters":{"Type":"ball"}},{"id":214,"name":"Reward: Chest - Event Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"39","Amount":0}},{"id":59,"name":"Reward: Spell - Random Core (x5)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"0","Amount":5}},{"id":6,"name":"Reward: Gold (x100)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":100}},{"id":189,"name":"Reward: Chest - Silver Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"3","Amount":0}},{"id":236,"name":"Reward: Spell - Random Pro (x4)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"1","Amount":4}},{"id":189,"name":"Reward: Chest - Silver Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"3","Amount":0}},{"id":173,"name":"Reward: Gold (x300)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":300}},{"id":237,"name":"Reward: Spell - Random Core (x40)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"0","Amount":40}},{"id":11,"name":"Reward: Gold (x500)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":500}},{"id":190,"name":"Reward: Chest - Golden Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"4","Amount":0}}]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        stream.writeVInt(6911)
        stream.writeStringReference('Survival - Triple Energy Rush - 10W3L - ElDorado - EventChest')
        stream.writeVInt(1)
        stream.writeVInt(1781179200)
        stream.writeVInt(1781264700)
        stream.writeVInt(1781092800)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Survival - Triple Energy Rush - 10W3L - ElDorado - EventChest')
        stream.writeString('{"Color":"#ae2d13","SurvivalLookup":"93","2v2":false,"lookupValues":[{"id":93,"name":"Survival - Triple Energy Rush - 10W3L - El Dorado - EventChest","lookup":"survival_event_lookup","parameters":{"JoinCost":20,"FreePass":1,"MaxWins":10,"MaxLoss":3,"ManaGeneration":300,"BallDensity":100,"BallScale":100,"NumberOfBalls":1,"NumberOfBallsOnOvertime":2,"ResetWinsOnRetry":false,"NameKey":"survival-triple-energy-rush-name","DescriptionKey":"survival-triple-energy-rush-desc","Arena":4,"BallType":"1","EndRewardChest":"214","IntermediateRewards":["59","6","189","236","189","173","237","11","190"],"GoaliesDisabled":false,"AllowPlayingAfterWin":false,"DisableDeckRandomization":false}},{"id":1,"name":"Ball: Normal","lookup":"ball_lookup","parameters":{"Type":"ball"}},{"id":214,"name":"Reward: Chest - Event Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"39","Amount":0}},{"id":59,"name":"Reward: Spell - Random Core (x5)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"0","Amount":5}},{"id":6,"name":"Reward: Gold (x100)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":100}},{"id":189,"name":"Reward: Chest - Silver Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"3","Amount":0}},{"id":236,"name":"Reward: Spell - Random Pro (x4)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"1","Amount":4}},{"id":189,"name":"Reward: Chest - Silver Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"3","Amount":0}},{"id":173,"name":"Reward: Gold (x300)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":300}},{"id":237,"name":"Reward: Spell - Random Core (x40)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"0","Amount":40}},{"id":11,"name":"Reward: Gold (x500)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":500}},{"id":190,"name":"Reward: Chest - Golden Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"4","Amount":0}}]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        stream.writeVInt(6912)
        stream.writeStringReference('Survival - Melon Mayhem - 8W3L - Greenfield - MiniChest')
        stream.writeVInt(1)
        stream.writeVInt(1780833600)
        stream.writeVInt(1780919100)
        stream.writeVInt(1780747200)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Survival - Melon Mayhem - 8W3L - Greenfield - MiniChest')
        stream.writeString('{"Color":"#ae2d13","SurvivalLookup":"251","2v2":false,"lookupValues":[{"id":251,"name":"Survival - Melon Mayhem - 8W3L - Greenfield - MiniChest","lookup":"survival_event_lookup","parameters":{"JoinCost":10,"FreePass":1,"MaxWins":8,"MaxLoss":3,"ManaGeneration":100,"BallDensity":100,"BallScale":100,"NumberOfBalls":3,"NumberOfBallsOnOvertime":4,"ResetWinsOnRetry":false,"NameKey":"survival-melon-mayhem-name","DescriptionKey":"survival-generic1-desc","Arena":1,"GoaliesDisabled":true,"DisableDeckRandomization":true,"BallType":"1","EndRewardChest":"74","Deck":["43","43","43","43"],"IntermediateRewards":["4","59","5","60","65","7","189"],"AllowPlayingAfterWin":false}},{"id":1,"name":"Ball: Normal","lookup":"ball_lookup","parameters":{"Type":"ball"}},{"id":74,"name":"Reward: Chest - Mini Event Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"16","Amount":0}},{"id":43,"name":"Spell: Melon","lookup":"spell_lookup","parameters":{"RefId":"melon"}},{"id":43,"name":"Spell: Melon","lookup":"spell_lookup","parameters":{"RefId":"melon"}},{"id":43,"name":"Spell: Melon","lookup":"spell_lookup","parameters":{"RefId":"melon"}},{"id":43,"name":"Spell: Melon","lookup":"spell_lookup","parameters":{"RefId":"melon"}},{"id":4,"name":"Reward: Gold (x25)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":25}},{"id":59,"name":"Reward: Spell - Random Core (x5)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"0","Amount":5}},{"id":5,"name":"Reward: Gold (x75)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":75}},{"id":60,"name":"Reward: Spell - Random Core (x10)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"0","Amount":10}},{"id":65,"name":"Reward: Spell - Random Pro (x3)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"1","Amount":3}},{"id":7,"name":"Reward: Gold (x150)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":150}},{"id":189,"name":"Reward: Chest - Silver Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"3","Amount":0}}]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        stream.writeVInt(6913)
        stream.writeStringReference('Survival - Core Rumblers Only - 10W3L - Greenfield - EventChest')
        stream.writeVInt(1)
        stream.writeVInt(1781006400)
        stream.writeVInt(1781091900)
        stream.writeVInt(1780920000)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Survival - Core Rumblers Only - 10W3L - Greenfield - EventChest')
        stream.writeString('{"Color":"#ae2d13","SurvivalLookup":"130","2v2":false,"lookupValues":[{"id":130,"name":"Survival - Core Rumblers Only - 10W3L - Greenfield - EventChest","lookup":"survival_event_lookup","parameters":{"JoinCost":20,"FreePass":1,"MaxWins":10,"MaxLoss":3,"ManaGeneration":100,"BallDensity":100,"BallScale":100,"NumberOfBalls":1,"NumberOfBallsOnOvertime":2,"ResetWinsOnRetry":true,"Arena":1,"NameKey":"survival-core-rumblers-only-name","DescriptionKey":"survival-core-rumblers-only-desc","BallType":"1","EndRewardChest":"214","Deck":["36","55","47","40","16","43","41","45"],"IntermediateRewards":["59","6","189","61","189","173","237","11","190"],"GoaliesDisabled":false,"AllowPlayingAfterWin":false,"DisableDeckRandomization":false}},{"id":1,"name":"Ball: Normal","lookup":"ball_lookup","parameters":{"Type":"ball"}},{"id":214,"name":"Reward: Chest - Event Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"39","Amount":0}},{"id":36,"name":"Spell: Lazy Panda","lookup":"spell_lookup","parameters":{"RefId":"pawn"}},{"id":55,"name":"Spell: Tiny Tanuki","lookup":"spell_lookup","parameters":{"RefId":"tanuki"}},{"id":47,"name":"Spell: Raging Bull","lookup":"spell_lookup","parameters":{"RefId":"bull"}},{"id":40,"name":"Spell: Loyal Dog","lookup":"spell_lookup","parameters":{"RefId":"support"}},{"id":16,"name":"Spell: Bomba","lookup":"spell_lookup","parameters":{"RefId":"bomb"}},{"id":43,"name":"Spell: Melon","lookup":"spell_lookup","parameters":{"RefId":"melon"}},{"id":41,"name":"Spell: Magnetman","lookup":"spell_lookup","parameters":{"RefId":"magnet"}},{"id":45,"name":"Spell: Mr. Fire","lookup":"spell_lookup","parameters":{"RefId":"explosive"}},{"id":59,"name":"Reward: Spell - Random Core (x5)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"0","Amount":5}},{"id":6,"name":"Reward: Gold (x100)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":100}},{"id":189,"name":"Reward: Chest - Silver Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"3","Amount":0}},{"id":61,"name":"Reward: Spell - Random Core (x20)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"0","Amount":20}},{"id":189,"name":"Reward: Chest - Silver Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"3","Amount":0}},{"id":173,"name":"Reward: Gold (x300)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":300}},{"id":237,"name":"Reward: Spell - Random Core (x40)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"0","Amount":40}},{"id":11,"name":"Reward: Gold (x500)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":500}},{"id":190,"name":"Reward: Chest - Golden Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"4","Amount":0}}]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        stream.writeVInt(6914)
        stream.writeStringReference('2v2 - Boom Rocket Madness - 20W- Greenfield - EventChest')
        stream.writeVInt(2)
        stream.writeVInt(1780315200)
        stream.writeVInt(1780400700)
        stream.writeVInt(1780228800)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('2v2 - Boom Rocket Madness - 20W- Greenfield - EventChest')
        stream.writeString('{"Color":"#ae2d13","2V2Lookup":"259","lookupValues":[{"id":259,"name":"2v2 - Boom Rocket Madness - 20W- Greenfield - EventChest","lookup":"2v2_event_lookup","parameters":{"NameKey":"survival-rocket-name","DescriptionKey":"survival-rocket-desc-2","GameModeConfig":{"GoaliesDisabled":true,"BallDensity":100,"BallScale":100,"NumberOfBallsOnOvertime":4,"DisableDeckRandomization":true,"ManaGeneration":200,"Arena":1,"NumberOfBalls":3},"BallType":"1","Deck":["18","18","18","18"],"IntermediateRewards":["59","6","189","236","189","173","237","11","190","214"],"WinsRequired":[2,4,6,8,10,12,14,16,18,20]}},{"id":1,"name":"Ball: Normal","lookup":"ball_lookup","parameters":{"Type":"ball"}},{"id":18,"name":"Spell: Boom Rocket","lookup":"spell_lookup","parameters":{"RefId":"rocket"}},{"id":18,"name":"Spell: Boom Rocket","lookup":"spell_lookup","parameters":{"RefId":"rocket"}},{"id":18,"name":"Spell: Boom Rocket","lookup":"spell_lookup","parameters":{"RefId":"rocket"}},{"id":18,"name":"Spell: Boom Rocket","lookup":"spell_lookup","parameters":{"RefId":"rocket"}},{"id":59,"name":"Reward: Spell - Random Core (x5)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"0","Amount":5}},{"id":6,"name":"Reward: Gold (x100)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":100}},{"id":189,"name":"Reward: Chest - Silver Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"3","Amount":0}},{"id":236,"name":"Reward: Spell - Random Pro (x4)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"1","Amount":4}},{"id":189,"name":"Reward: Chest - Silver Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"3","Amount":0}},{"id":173,"name":"Reward: Gold (x300)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":300}},{"id":237,"name":"Reward: Spell - Random Core (x40)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"0","Amount":40}},{"id":11,"name":"Reward: Gold (x500)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":500}},{"id":190,"name":"Reward: Chest - Golden Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"4","Amount":0}},{"id":214,"name":"Reward: Chest - Event Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"39","Amount":0}}]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        stream.writeVInt(6915)
        stream.writeStringReference('2v2 - Boom Rocket Madness - 20W- Greenfield - EventChest')
        stream.writeVInt(2)
        stream.writeVInt(1780920000)
        stream.writeVInt(1781005500)
        stream.writeVInt(1780833600)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('2v2 - Boom Rocket Madness - 20W- Greenfield - EventChest')
        stream.writeString('{"Color":"#ae2d13","2V2Lookup":"259","lookupValues":[{"id":259,"name":"2v2 - Boom Rocket Madness - 20W- Greenfield - EventChest","lookup":"2v2_event_lookup","parameters":{"NameKey":"survival-rocket-name","DescriptionKey":"survival-rocket-desc-2","GameModeConfig":{"GoaliesDisabled":true,"BallDensity":100,"BallScale":100,"NumberOfBallsOnOvertime":4,"DisableDeckRandomization":true,"ManaGeneration":200,"Arena":1,"NumberOfBalls":3},"BallType":"1","Deck":["18","18","18","18"],"IntermediateRewards":["59","6","189","236","189","173","237","11","190","214"],"WinsRequired":[2,4,6,8,10,12,14,16,18,20]}},{"id":1,"name":"Ball: Normal","lookup":"ball_lookup","parameters":{"Type":"ball"}},{"id":18,"name":"Spell: Boom Rocket","lookup":"spell_lookup","parameters":{"RefId":"rocket"}},{"id":18,"name":"Spell: Boom Rocket","lookup":"spell_lookup","parameters":{"RefId":"rocket"}},{"id":18,"name":"Spell: Boom Rocket","lookup":"spell_lookup","parameters":{"RefId":"rocket"}},{"id":18,"name":"Spell: Boom Rocket","lookup":"spell_lookup","parameters":{"RefId":"rocket"}},{"id":59,"name":"Reward: Spell - Random Core (x5)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"0","Amount":5}},{"id":6,"name":"Reward: Gold (x100)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":100}},{"id":189,"name":"Reward: Chest - Silver Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"3","Amount":0}},{"id":236,"name":"Reward: Spell - Random Pro (x4)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"1","Amount":4}},{"id":189,"name":"Reward: Chest - Silver Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"3","Amount":0}},{"id":173,"name":"Reward: Gold (x300)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":300}},{"id":237,"name":"Reward: Spell - Random Core (x40)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"0","Amount":40}},{"id":11,"name":"Reward: Gold (x500)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":500}},{"id":190,"name":"Reward: Chest - Golden Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"4","Amount":0}},{"id":214,"name":"Reward: Chest - Event Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"39","Amount":0}}]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        stream.writeVInt(6916)
        stream.writeStringReference('2v2 - Own Lineup - 20W - ElDorado - EventChest')
        stream.writeVInt(2)
        stream.writeVInt(1780488000)
        stream.writeVInt(1780573500)
        stream.writeVInt(1780401600)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('2v2 - Own Lineup - 20W - ElDorado - EventChest')
        stream.writeString('{"Color":"#ae2d13","2V2Lookup":"256","lookupValues":[{"id":256,"name":"2v2 - Own Lineup - 20W - ElDorado - EventChest","lookup":"2v2_event_lookup","parameters":{"NameKey":"survival-2v2-name","DescriptionKey":"survival-2v2-desc-1","GameModeConfig":{"GoaliesDisabled":false,"BallDensity":100,"BallScale":100,"NumberOfBallsOnOvertime":2,"DisableDeckRandomization":false,"ManaGeneration":100,"Arena":4,"NumberOfBalls":1},"BallType":"1","WinsRequired":[2,4,6,8,10,12,14,16,18,20],"IntermediateRewards":["59","6","189","236","189","173","237","11","190","214"]}},{"id":1,"name":"Ball: Normal","lookup":"ball_lookup","parameters":{"Type":"ball"}},{"id":59,"name":"Reward: Spell - Random Core (x5)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"0","Amount":5}},{"id":6,"name":"Reward: Gold (x100)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":100}},{"id":189,"name":"Reward: Chest - Silver Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"3","Amount":0}},{"id":236,"name":"Reward: Spell - Random Pro (x4)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"1","Amount":4}},{"id":189,"name":"Reward: Chest - Silver Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"3","Amount":0}},{"id":173,"name":"Reward: Gold (x300)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":300}},{"id":237,"name":"Reward: Spell - Random Core (x40)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"0","Amount":40}},{"id":11,"name":"Reward: Gold (x500)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":500}},{"id":190,"name":"Reward: Chest - Golden Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"4","Amount":0}},{"id":214,"name":"Reward: Chest - Event Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"39","Amount":0}}]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        stream.writeVInt(6917)
        stream.writeStringReference('2v2 - Own Lineup - 20W - ElDorado - EventChest')
        stream.writeVInt(2)
        stream.writeVInt(1781092800)
        stream.writeVInt(1781178300)
        stream.writeVInt(1781006400)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('2v2 - Own Lineup - 20W - ElDorado - EventChest')
        stream.writeString('{"Color":"#ae2d13","2V2Lookup":"256","lookupValues":[{"id":256,"name":"2v2 - Own Lineup - 20W - ElDorado - EventChest","lookup":"2v2_event_lookup","parameters":{"NameKey":"survival-2v2-name","DescriptionKey":"survival-2v2-desc-1","GameModeConfig":{"GoaliesDisabled":false,"BallDensity":100,"BallScale":100,"NumberOfBallsOnOvertime":2,"DisableDeckRandomization":false,"ManaGeneration":100,"Arena":4,"NumberOfBalls":1},"BallType":"1","WinsRequired":[2,4,6,8,10,12,14,16,18,20],"IntermediateRewards":["59","6","189","236","189","173","237","11","190","214"]}},{"id":1,"name":"Ball: Normal","lookup":"ball_lookup","parameters":{"Type":"ball"}},{"id":59,"name":"Reward: Spell - Random Core (x5)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"0","Amount":5}},{"id":6,"name":"Reward: Gold (x100)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":100}},{"id":189,"name":"Reward: Chest - Silver Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"3","Amount":0}},{"id":236,"name":"Reward: Spell - Random Pro (x4)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"1","Amount":4}},{"id":189,"name":"Reward: Chest - Silver Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"3","Amount":0}},{"id":173,"name":"Reward: Gold (x300)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":300}},{"id":237,"name":"Reward: Spell - Random Core (x40)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"0","Amount":40}},{"id":11,"name":"Reward: Gold (x500)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":500}},{"id":190,"name":"Reward: Chest - Golden Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"4","Amount":0}},{"id":214,"name":"Reward: Chest - Event Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"39","Amount":0}}]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        stream.writeVInt(6918)
        stream.writeStringReference('2v2 - No Goalie - 20W - ZenPalace - EpicChest')
        stream.writeVInt(2)
        stream.writeVInt(1780660800)
        stream.writeVInt(1780832700)
        stream.writeVInt(1780574400)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('2v2 - No Goalie - 20W - ZenPalace - EpicChest')
        stream.writeString('{"Color":"#ae2d13","2V2Lookup":"258","lookupValues":[{"id":258,"name":"2v2 - No Goalie - 20W - ZenPalace - EpicChest","lookup":"2v2_event_lookup","parameters":{"NameKey":"survival-no-goalie-name","DescriptionKey":"survival-no-goalie-desc","GameModeConfig":{"GoaliesDisabled":true,"BallDensity":100,"BallScale":100,"NumberOfBallsOnOvertime":2,"DisableDeckRandomization":false,"ManaGeneration":100,"Arena":7,"NumberOfBalls":1},"BallType":"1","IntermediateRewards":["236","189","173","237","190","238","228","190","150","76"],"WinsRequired":[2,4,6,8,10,12,14,16,18,20]}},{"id":1,"name":"Ball: Normal","lookup":"ball_lookup","parameters":{"Type":"ball"}},{"id":236,"name":"Reward: Spell - Random Pro (x4)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"1","Amount":4}},{"id":189,"name":"Reward: Chest - Silver Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"3","Amount":0}},{"id":173,"name":"Reward: Gold (x300)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":300}},{"id":237,"name":"Reward: Spell - Random Core (x40)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"0","Amount":40}},{"id":190,"name":"Reward: Chest - Golden Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"4","Amount":0}},{"id":238,"name":"Reward: Gold (x600)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":600}},{"id":228,"name":"Reward: Spell - Random Pro (x16)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"1","Amount":16}},{"id":190,"name":"Reward: Chest - Golden Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"4","Amount":0}},{"id":150,"name":"Reward: Spell - Random Superstar (x1)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"2","Amount":1}},{"id":76,"name":"Reward: Chest - Epic Event Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"18","Amount":0}}]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        stream.writeVInt(6920)
        stream.writeStringReference('2v2 - Explosive Madness - 20W - Greenfield - EventChest')
        stream.writeVInt(2)
        stream.writeVInt(1780401600)
        stream.writeVInt(1780487100)
        stream.writeVInt(1780315200)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('2v2 - Explosive Madness - 20W - Greenfield - EventChest')
        stream.writeString('{"Color":"#ae2d13","2V2Lookup":"255","lookupValues":[{"id":255,"name":"2v2 - Explosive Madness - 20W - Greenfield - EventChest","lookup":"2v2_event_lookup","parameters":{"NameKey":"survival-explosion-mayhem-name","DescriptionKey":"survival-explosion-mayhem-desc","GameModeConfig":{"GoaliesDisabled":true,"BallDensity":100,"BallScale":100,"NumberOfBallsOnOvertime":4,"DisableDeckRandomization":true,"ManaGeneration":200,"Arena":1,"NumberOfBalls":3},"BallType":"1","Deck":["45","45","45","45"],"WinsRequired":[2,4,6,8,10,12,14,16,18,20],"IntermediateRewards":["59","6","189","236","189","173","237","11","190","214"]}},{"id":1,"name":"Ball: Normal","lookup":"ball_lookup","parameters":{"Type":"ball"}},{"id":45,"name":"Spell: Mr. Fire","lookup":"spell_lookup","parameters":{"RefId":"explosive"}},{"id":45,"name":"Spell: Mr. Fire","lookup":"spell_lookup","parameters":{"RefId":"explosive"}},{"id":45,"name":"Spell: Mr. Fire","lookup":"spell_lookup","parameters":{"RefId":"explosive"}},{"id":45,"name":"Spell: Mr. Fire","lookup":"spell_lookup","parameters":{"RefId":"explosive"}},{"id":59,"name":"Reward: Spell - Random Core (x5)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"0","Amount":5}},{"id":6,"name":"Reward: Gold (x100)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":100}},{"id":189,"name":"Reward: Chest - Silver Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"3","Amount":0}},{"id":236,"name":"Reward: Spell - Random Pro (x4)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"1","Amount":4}},{"id":189,"name":"Reward: Chest - Silver Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"3","Amount":0}},{"id":173,"name":"Reward: Gold (x300)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":300}},{"id":237,"name":"Reward: Spell - Random Core (x40)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"0","Amount":40}},{"id":11,"name":"Reward: Gold (x500)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":500}},{"id":190,"name":"Reward: Chest - Golden Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"4","Amount":0}},{"id":214,"name":"Reward: Chest - Event Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"39","Amount":0}}]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        stream.writeVInt(6922)
        stream.writeStringReference('2v2 - Explosive Madness - 20W - Greenfield - EventChest')
        stream.writeVInt(2)
        stream.writeVInt(1781006400)
        stream.writeVInt(1781091900)
        stream.writeVInt(1780920000)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('2v2 - Explosive Madness - 20W - Greenfield - EventChest')
        stream.writeString('{"Color":"#ae2d13","2V2Lookup":"255","lookupValues":[{"id":255,"name":"2v2 - Explosive Madness - 20W - Greenfield - EventChest","lookup":"2v2_event_lookup","parameters":{"NameKey":"survival-explosion-mayhem-name","DescriptionKey":"survival-explosion-mayhem-desc","GameModeConfig":{"GoaliesDisabled":true,"BallDensity":100,"BallScale":100,"NumberOfBallsOnOvertime":4,"DisableDeckRandomization":true,"ManaGeneration":200,"Arena":1,"NumberOfBalls":3},"BallType":"1","Deck":["45","45","45","45"],"WinsRequired":[2,4,6,8,10,12,14,16,18,20],"IntermediateRewards":["59","6","189","236","189","173","237","11","190","214"]}},{"id":1,"name":"Ball: Normal","lookup":"ball_lookup","parameters":{"Type":"ball"}},{"id":45,"name":"Spell: Mr. Fire","lookup":"spell_lookup","parameters":{"RefId":"explosive"}},{"id":45,"name":"Spell: Mr. Fire","lookup":"spell_lookup","parameters":{"RefId":"explosive"}},{"id":45,"name":"Spell: Mr. Fire","lookup":"spell_lookup","parameters":{"RefId":"explosive"}},{"id":45,"name":"Spell: Mr. Fire","lookup":"spell_lookup","parameters":{"RefId":"explosive"}},{"id":59,"name":"Reward: Spell - Random Core (x5)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"0","Amount":5}},{"id":6,"name":"Reward: Gold (x100)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":100}},{"id":189,"name":"Reward: Chest - Silver Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"3","Amount":0}},{"id":236,"name":"Reward: Spell - Random Pro (x4)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"1","Amount":4}},{"id":189,"name":"Reward: Chest - Silver Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"3","Amount":0}},{"id":173,"name":"Reward: Gold (x300)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":300}},{"id":237,"name":"Reward: Spell - Random Core (x40)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"0","Amount":40}},{"id":11,"name":"Reward: Gold (x500)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":500}},{"id":190,"name":"Reward: Chest - Golden Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"4","Amount":0}},{"id":214,"name":"Reward: Chest - Event Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"39","Amount":0}}]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        stream.writeVInt(6923)
        stream.writeStringReference('2v2 - Melon Mayhem - 16W - Greenfield - MiniChest')
        stream.writeVInt(2)
        stream.writeVInt(1780574400)
        stream.writeVInt(1780659900)
        stream.writeVInt(1780488000)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('2v2 - Melon Mayhem - 16W - Greenfield - MiniChest')
        stream.writeString('{"Color":"#ae2d13","2V2Lookup":"264","lookupValues":[{"id":264,"name":"2v2 - Melon Mayhem - 16W - Greenfield - MiniChest","lookup":"2v2_event_lookup","parameters":{"NameKey":"survival-melon-mayhem-name","DescriptionKey":"survival-generic1-desc","GameModeConfig":{"GoaliesDisabled":true,"BallDensity":100,"BallScale":100,"NumberOfBallsOnOvertime":4,"DisableDeckRandomization":true,"ManaGeneration":100,"Arena":1,"NumberOfBalls":3},"BallType":"1","Deck":["43","43","43","43"],"IntermediateRewards":["4","59","5","60","65","7","189","74"],"WinsRequired":[2,4,6,8,10,12,14,16]}},{"id":1,"name":"Ball: Normal","lookup":"ball_lookup","parameters":{"Type":"ball"}},{"id":43,"name":"Spell: Melon","lookup":"spell_lookup","parameters":{"RefId":"melon"}},{"id":43,"name":"Spell: Melon","lookup":"spell_lookup","parameters":{"RefId":"melon"}},{"id":43,"name":"Spell: Melon","lookup":"spell_lookup","parameters":{"RefId":"melon"}},{"id":43,"name":"Spell: Melon","lookup":"spell_lookup","parameters":{"RefId":"melon"}},{"id":4,"name":"Reward: Gold (x25)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":25}},{"id":59,"name":"Reward: Spell - Random Core (x5)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"0","Amount":5}},{"id":5,"name":"Reward: Gold (x75)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":75}},{"id":60,"name":"Reward: Spell - Random Core (x10)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"0","Amount":10}},{"id":65,"name":"Reward: Spell - Random Pro (x3)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"1","Amount":3}},{"id":7,"name":"Reward: Gold (x150)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":150}},{"id":189,"name":"Reward: Chest - Silver Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"3","Amount":0}},{"id":74,"name":"Reward: Chest - Mini Event Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"16","Amount":0}}]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        stream.writeVInt(6924)
        stream.writeStringReference('2v2 - Melon Mayhem - 16W - Greenfield - MiniChest')
        stream.writeVInt(2)
        stream.writeVInt(1781179200)
        stream.writeVInt(1781264700)
        stream.writeVInt(1781092800)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('2v2 - Melon Mayhem - 16W - Greenfield - MiniChest')
        stream.writeString('{"Color":"#ae2d13","2V2Lookup":"264","lookupValues":[{"id":264,"name":"2v2 - Melon Mayhem - 16W - Greenfield - MiniChest","lookup":"2v2_event_lookup","parameters":{"NameKey":"survival-melon-mayhem-name","DescriptionKey":"survival-generic1-desc","GameModeConfig":{"GoaliesDisabled":true,"BallDensity":100,"BallScale":100,"NumberOfBallsOnOvertime":4,"DisableDeckRandomization":true,"ManaGeneration":100,"Arena":1,"NumberOfBalls":3},"BallType":"1","Deck":["43","43","43","43"],"IntermediateRewards":["4","59","5","60","65","7","189","74"],"WinsRequired":[2,4,6,8,10,12,14,16]}},{"id":1,"name":"Ball: Normal","lookup":"ball_lookup","parameters":{"Type":"ball"}},{"id":43,"name":"Spell: Melon","lookup":"spell_lookup","parameters":{"RefId":"melon"}},{"id":43,"name":"Spell: Melon","lookup":"spell_lookup","parameters":{"RefId":"melon"}},{"id":43,"name":"Spell: Melon","lookup":"spell_lookup","parameters":{"RefId":"melon"}},{"id":43,"name":"Spell: Melon","lookup":"spell_lookup","parameters":{"RefId":"melon"}},{"id":4,"name":"Reward: Gold (x25)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":25}},{"id":59,"name":"Reward: Spell - Random Core (x5)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"0","Amount":5}},{"id":5,"name":"Reward: Gold (x75)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":75}},{"id":60,"name":"Reward: Spell - Random Core (x10)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"0","Amount":10}},{"id":65,"name":"Reward: Spell - Random Pro (x3)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"1","Amount":3}},{"id":7,"name":"Reward: Gold (x150)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":150}},{"id":189,"name":"Reward: Chest - Silver Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"3","Amount":0}},{"id":74,"name":"Reward: Chest - Mini Event Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"16","Amount":0}}]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        stream.writeVInt(6925)
        stream.writeStringReference('2v2 - Triple Energy Rush - 20W - El Dorado - Event Chest')
        stream.writeVInt(2)
        stream.writeVInt(1780833600)
        stream.writeVInt(1780919100)
        stream.writeVInt(1780747200)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('2v2 - Triple Energy Rush - 20W - El Dorado - Event Chest')
        stream.writeString('{"Color":"#ae2d13","2V2Lookup":"293","lookupValues":[{"id":293,"name":"2v2 - Triple Energy Rush - 20W - El Dorado - Event Chest","lookup":"2v2_event_lookup","parameters":{"NameKey":"survival-triple-energy-rush-name","DescriptionKey":"survival-triple-energy-rush-desc","GameModeConfig":{"GoaliesDisabled":false,"BallDensity":100,"BallScale":100,"NumberOfBallsOnOvertime":2,"DisableDeckRandomization":false,"ManaGeneration":300,"Arena":4,"NumberOfBalls":1},"BallType":"1","IntermediateRewards":["59","6","189","236","189","173","237","11","190","214"],"WinsRequired":[2,4,6,8,10,12,14,16,18,20]}},{"id":1,"name":"Ball: Normal","lookup":"ball_lookup","parameters":{"Type":"ball"}},{"id":59,"name":"Reward: Spell - Random Core (x5)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"0","Amount":5}},{"id":6,"name":"Reward: Gold (x100)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":100}},{"id":189,"name":"Reward: Chest - Silver Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"3","Amount":0}},{"id":236,"name":"Reward: Spell - Random Pro (x4)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"1","Amount":4}},{"id":189,"name":"Reward: Chest - Silver Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"3","Amount":0}},{"id":173,"name":"Reward: Gold (x300)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":300}},{"id":237,"name":"Reward: Spell - Random Core (x40)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"0","Amount":40}},{"id":11,"name":"Reward: Gold (x500)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":500}},{"id":190,"name":"Reward: Chest - Golden Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"4","Amount":0}},{"id":214,"name":"Reward: Chest - Event Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"39","Amount":0}}]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        stream.writeVInt(6927)
        stream.writeStringReference('Cup: (2022) Own Line UP 16p')
        stream.writeVInt(4)
        stream.writeVInt(1780315200)
        stream.writeVInt(1780573500)
        stream.writeVInt(1780228800)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Cup: (2022) Own Line UP 16p')
        stream.writeString('{"Color":"#ae2d13","CupLookup":"374","lookupValues":[{"id":374,"name":"Cup - (2022) Own Lineup - 16P - Greenfield - SuperEventChest","lookup":"cup_event_lookup","parameters":{"JoinCost":20,"FreeEntriesCount":0,"PlayerCount":16,"GameModeConfig":{"GoaliesDisabled":false,"BallDensity":100,"BallScale":100,"NumberOfBallsOnOvertime":2,"DisableDeckRandomization":false,"ManaGeneration":100,"Arena":4,"NumberOfBalls":1},"BallType":"1","IntermediateRewards":["11","114","201"],"EndRewards":["190","74","214"],"FinalReward":"75","NameKey":"survival-generic1-name","DescriptionKey":"survival-generic4-desc"}},{"id":1,"name":"Ball: Normal","lookup":"ball_lookup","parameters":{"Type":"ball"}},{"id":11,"name":"Reward: Gold (x500)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":500}},{"id":114,"name":"Reward: Gold (x1000)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":1000}},{"id":201,"name":"Reward: Gold (x1500)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":1500}},{"id":190,"name":"Reward: Chest - Golden Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"4","Amount":0}},{"id":74,"name":"Reward: Chest - Mini Event Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"16","Amount":0}},{"id":214,"name":"Reward: Chest - Event Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"39","Amount":0}},{"id":75,"name":"Reward: Chest - Rare Event Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"17","Amount":0}}]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        stream.writeVInt(6928)
        stream.writeStringReference('Cup: (2022) Own Line Up 8p')
        stream.writeVInt(4)
        stream.writeVInt(1780747200)
        stream.writeVInt(1780919100)
        stream.writeVInt(1780660800)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Cup: (2022) Own Line Up 8p')
        stream.writeString('{"Color":"#ae2d13","CupLookup":"373","lookupValues":[{"id":373,"name":"Cup -  (2022) Own Lineup - 8P - FrozenValley - EventChest","lookup":"cup_event_lookup","parameters":{"JoinCost":10,"FreeEntriesCount":0,"PlayerCount":8,"GameModeConfig":{"GoaliesDisabled":false,"BallDensity":100,"BallScale":100,"NumberOfBallsOnOvertime":2,"DisableDeckRandomization":false,"ManaGeneration":100,"Arena":10,"NumberOfBalls":1},"BallType":"1","IntermediateRewards":["9","12"],"EndRewards":["190","74"],"FinalReward":"214","NameKey":"survival-generic1-name","DescriptionKey":"survival-generic4-desc"}},{"id":1,"name":"Ball: Normal","lookup":"ball_lookup","parameters":{"Type":"ball"}},{"id":9,"name":"Reward: Gold (x250)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":250}},{"id":12,"name":"Reward: Gold (x750)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":750}},{"id":190,"name":"Reward: Chest - Golden Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"4","Amount":0}},{"id":74,"name":"Reward: Chest - Mini Event Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"16","Amount":0}},{"id":214,"name":"Reward: Chest - Event Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"39","Amount":0}}]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        stream.writeVInt(6929)
        stream.writeStringReference('Cup: (2022) Own Line Up 32p')
        stream.writeVInt(4)
        stream.writeVInt(1781179200)
        stream.writeVInt(1781351100)
        stream.writeVInt(1781092800)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Cup: (2022) Own Line Up 32p')
        stream.writeString('{"Color":"#ae2d13","CupLookup":"378","lookupValues":[{"id":378,"name":"Cup - (2022) Own Lineup - 32P - Premier - RareEventChest","lookup":"cup_event_lookup","parameters":{"JoinCost":100,"FreeEntriesCount":0,"PlayerCount":32,"GameModeConfig":{"GoaliesDisabled":false,"BallDensity":100,"BallScale":100,"NumberOfBallsOnOvertime":2,"DisableDeckRandomization":false,"ManaGeneration":100,"Arena":16,"NumberOfBalls":1},"BallType":"1","IntermediateRewards":["194","195","379","380"],"EndRewards":["190","74","214","75"],"FinalReward":"76","NameKey":"survival-generic1-name","DescriptionKey":"survival-generic4-desc"}},{"id":1,"name":"Ball: Normal","lookup":"ball_lookup","parameters":{"Type":"ball"}},{"id":194,"name":"Reward: Gold (x4000)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":4000}},{"id":195,"name":"Reward: Gold (x5000)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":5000}},{"id":379,"name":"Reward: Gold (x6000)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":6000}},{"id":380,"name":"Reward: Gold (x7000)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":7000}},{"id":190,"name":"Reward: Chest - Golden Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"4","Amount":0}},{"id":74,"name":"Reward: Chest - Mini Event Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"16","Amount":0}},{"id":214,"name":"Reward: Chest - Event Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"39","Amount":0}},{"id":75,"name":"Reward: Chest - Rare Event Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"17","Amount":0}},{"id":76,"name":"Reward: Chest - Epic Event Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"18","Amount":0}}]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        stream.writeVInt(6930)
        stream.writeStringReference('Cup: (2022) Beach Ball 32p')
        stream.writeVInt(4)
        stream.writeVInt(1780574400)
        stream.writeVInt(1780746300)
        stream.writeVInt(1780488000)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Cup: (2022) Beach Ball 32p')
        stream.writeString('{"CupLookup":"383","Color":"#ae2d13","lookupValues":[{"id":383,"name":"Cup - (2022) Beach Ball Showdown - 32P - Greenfield -  Rare Event Chest","lookup":"cup_event_lookup","parameters":{"JoinCost":100,"FreeEntriesCount":0,"PlayerCount":32,"NameKey":"survival-beachball-showdown-name","DescriptionKey":"survival-generic4-desc","GameModeConfig":{"GoaliesDisabled":false,"BallDensity":100,"BallScale":100,"NumberOfBallsOnOvertime":2,"DisableDeckRandomization":false,"ManaGeneration":100,"Arena":1,"NumberOfBalls":1},"BallType":"2","IntermediateRewards":["194","195","202","380"],"EndRewards":["190","74","214","75"],"FinalReward":"76"}},{"id":2,"name":"Ball: Beach ball","lookup":"ball_lookup","parameters":{"Type":"beachball"}},{"id":194,"name":"Reward: Gold (x4000)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":4000}},{"id":195,"name":"Reward: Gold (x5000)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":5000}},{"id":202,"name":"Reward: Gold (x6000)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":6000}},{"id":380,"name":"Reward: Gold (x7000)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":7000}},{"id":190,"name":"Reward: Chest - Golden Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"4","Amount":0}},{"id":74,"name":"Reward: Chest - Mini Event Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"16","Amount":0}},{"id":214,"name":"Reward: Chest - Event Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"39","Amount":0}},{"id":75,"name":"Reward: Chest - Rare Event Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"17","Amount":0}},{"id":76,"name":"Reward: Chest - Epic Event Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"18","Amount":0}}]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        stream.writeVInt(6932)
        stream.writeStringReference('Cup - (2022) Bowling Showdown - 16P')
        stream.writeVInt(4)
        stream.writeVInt(1780920000)
        stream.writeVInt(1781178300)
        stream.writeVInt(1780833600)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Cup - (2022) Bowling Showdown - 16P')
        stream.writeString('{"Color":"#ae2d13","CupLookup":"385","lookupValues":[{"id":385,"name":"Cup - (2022) Bowling Showdown - 16P - El Dorado - Event Chest","lookup":"cup_event_lookup","parameters":{"JoinCost":20,"FreeEntriesCount":0,"PlayerCount":16,"GameModeConfig":{"GoaliesDisabled":false,"BallDensity":100,"BallScale":100,"NumberOfBallsOnOvertime":2,"DisableDeckRandomization":false,"ManaGeneration":100,"Arena":4,"NumberOfBalls":1},"BallType":"3","IntermediateRewards":["11","114","201"],"EndRewards":["190","74","214"],"FinalReward":"75","NameKey":"survival-bowling-showdown-name","DescriptionKey":"survival-rumble-showdown-desc"}},{"id":3,"name":"Ball: Bowling ball","lookup":"ball_lookup","parameters":{"Type":"bowlingball"}},{"id":11,"name":"Reward: Gold (x500)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":500}},{"id":114,"name":"Reward: Gold (x1000)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":1000}},{"id":201,"name":"Reward: Gold (x1500)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":1500}},{"id":190,"name":"Reward: Chest - Golden Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"4","Amount":0}},{"id":74,"name":"Reward: Chest - Mini Event Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"16","Amount":0}},{"id":214,"name":"Reward: Chest - Event Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"39","Amount":0}},{"id":75,"name":"Reward: Chest - Rare Event Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"17","Amount":0}}]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        stream.writeVInt(6933)
        stream.writeStringReference('Offer - An Offer Full Of Love - love-1 (Gift A)')
        stream.writeVInt(0)
        stream.writeVInt(1780272900)
        stream.writeVInt(1780444740)
        stream.writeVInt(1780272900)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Offer - An Offer Full Of Love - love-1 (Gift A)')
        stream.writeString('{"Color":"#448932","ShopSpenderDaysInActive":7,"ShopSpenderPercentageIncrease":50,"ShopSpenderCapWeekly":true,"ShopSpenderCapMonthly":true,"ShopSpenderCapAllTime":true,"OverrideName":"chronos-special-offer-love-1","TierDefaultShopItem":"7004010","Tier1ShopItem":"7004001","Tier2ShopItem":"7004002","Tier3ShopItem":"7004003","Tier4ShopItem":"7004003","Tier5ShopItem":"7004005","Tier6ShopItem":"7004005","Tier7ShopItem":"7004007","Tier8ShopItem":"7004007","Tier9ShopItem":"7004007","Tier10ShopItem":"7004010","Tier15ShopItem":"7004015","Tier20ShopItem":"7004020","Tier50ShopItem":"7004050","Tier60ShopItem":"7004060","lookupValues":[]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        stream.writeVInt(6936)
        stream.writeStringReference('Offer - Recommended by your Goalie! - football-8 (POWER CHEST)  ')
        stream.writeVInt(0)
        stream.writeVInt(1780445700)
        stream.writeVInt(1780617540)
        stream.writeVInt(1780445700)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Offer - Recommended by your Goalie! - football-8 (POWER CHEST)  ')
        stream.writeString('{"Color":"#448932","ShopSpenderDaysInActive":7,"ShopSpenderPercentageIncrease":50,"ShopSpenderCapWeekly":true,"ShopSpenderCapMonthly":true,"ShopSpenderCapAllTime":true,"OverrideName":"chronos-special-offer-football-8","TierDefaultShopItem":"7022001","Tier1ShopItem":"7022001","Tier2ShopItem":"7022002","Tier3ShopItem":"7022003","Tier4ShopItem":"7022003","Tier5ShopItem":"7022005","Tier6ShopItem":"7022005","Tier7ShopItem":"7022007","Tier8ShopItem":"7022007","Tier9ShopItem":"7022007","Tier10ShopItem":"7022010","Tier15ShopItem":"7022015","Tier20ShopItem":"7022020","Tier50ShopItem":"7022050","Tier60ShopItem":"7022060","lookupValues":[]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        stream.writeVInt(6937)
        stream.writeStringReference('Offer: Hero Chest C - 7 - "football-9"')
        stream.writeVInt(0)
        stream.writeVInt(1780964100)
        stream.writeVInt(1781135940)
        stream.writeVInt(1780964100)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Offer: Hero Chest C - 7 - "football-9"')
        stream.writeString('{"Color":"#448932","ShopSpenderDaysInActive":7,"ShopSpenderPercentageIncrease":50,"ShopSpenderCapWeekly":true,"ShopSpenderCapMonthly":true,"ShopSpenderCapAllTime":true,"OverrideName":"chronos-special-offer-football-9","TierDefaultShopItem":"7016007","Tier1ShopItem":"7016007","Tier2ShopItem":"7016007","Tier3ShopItem":"7016007","Tier4ShopItem":"7016007","Tier5ShopItem":"7016007","Tier6ShopItem":"7016007","Tier7ShopItem":"7016007","Tier8ShopItem":"7016007","Tier9ShopItem":"7016007","Tier10ShopItem":"7016010","Tier15ShopItem":"7016015","Tier20ShopItem":"7016020","Tier50ShopItem":"7016050","Tier60ShopItem":"7016060","lookupValues":[]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        stream.writeVInt(6941)
        stream.writeStringReference('Offer - Power Up with This! - boost-4 (Booster C)')
        stream.writeVInt(0)
        stream.writeVInt(1780618500)
        stream.writeVInt(1780790340)
        stream.writeVInt(1780618500)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Offer - Power Up with This! - boost-4 (Booster C)')
        stream.writeString('{"Color":"#448932","ShopSpenderDaysInActive":7,"ShopSpenderPercentageIncrease":50,"ShopSpenderCapWeekly":true,"ShopSpenderCapMonthly":true,"ShopSpenderCapAllTime":true,"OverrideName":"chronos-special-offer-boost-4","TierDefaultShopItem":"7003020","Tier1ShopItem":"7003010","Tier2ShopItem":"7003010","Tier3ShopItem":"7003010","Tier4ShopItem":"7003010","Tier5ShopItem":"7003010","Tier6ShopItem":"7003010","Tier7ShopItem":"7003010","Tier8ShopItem":"7003010","Tier9ShopItem":"7003010","Tier10ShopItem":"7003010","Tier15ShopItem":"7003015","Tier20ShopItem":"7003020","Tier50ShopItem":"7003050","Tier60ShopItem":"7003060","lookupValues":[]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        stream.writeVInt(6943)
        stream.writeStringReference('Offer - Celebrating your Progress - GLORY A - 1 - (glory-1)')
        stream.writeVInt(0)
        stream.writeVInt(1780791300)
        stream.writeVInt(1780963140)
        stream.writeVInt(1780791300)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Offer - Celebrating your Progress - GLORY A - 1 - (glory-1)')
        stream.writeString('{"Color":"#448932","ShopSpenderDaysInActive":7,"ShopSpenderPercentageIncrease":50,"ShopSpenderCapWeekly":true,"ShopSpenderCapMonthly":true,"ShopSpenderCapAllTime":true,"OverrideName":"chronos-special-offer-glory-1","TierDefaultShopItem":"7010001","Tier1ShopItem":"7010001","Tier2ShopItem":"7010002","Tier3ShopItem":"7010003","Tier4ShopItem":"7010003","Tier5ShopItem":"7010005","Tier6ShopItem":"7010005","Tier7ShopItem":"7010007","Tier8ShopItem":"7010007","Tier9ShopItem":"7010007","Tier10ShopItem":"7010010","Tier15ShopItem":"7010015","Tier20ShopItem":"7010020","Tier50ShopItem":"7010050","Tier60ShopItem":"7010060","lookupValues":[]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        stream.writeVInt(6948)
        stream.writeStringReference('Gold Battle Chest')
        stream.writeVInt(3)
        stream.writeVInt(1780488000)
        stream.writeVInt(1780573500)
        stream.writeVInt(1780488000)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Gold Battle Chest')
        stream.writeString('{"GlobalEventMode":"1","Color":"#ffba00","lookupValues":[]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        stream.writeVInt(6949)
        stream.writeStringReference('Gold Battle Chest')
        stream.writeVInt(3)
        stream.writeVInt(1781092800)
        stream.writeVInt(1781178300)
        stream.writeVInt(1781092800)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Gold Battle Chest')
        stream.writeString('{"GlobalEventMode":"1","Color":"#ffba00","lookupValues":[]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        stream.writeVInt(6953)
        stream.writeStringReference('Gift: Weekend Gift (Gems x100)')
        stream.writeVInt(9)
        stream.writeVInt(1780747200)
        stream.writeVInt(1780832700)
        stream.writeVInt(1780747200)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Gift: Weekend Gift (Gems x100)')
        stream.writeString('{"Color":"#ae2d13","Title":"chronos-gift-gems-description-2","Description":"chronos-gift-gems-description","DonationReward":"115","lookupValues":[{"id":115,"name":"Reward: Gems (x100)","lookup":"reward_lookup","parameters":{"Type":"Gems","RefId":"-1","Amount":100}}]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        stream.writeVInt(6955)
        stream.writeStringReference('Survival - Special Challenge Heavy Rat - 8W3L - Zen Palace - EventChest/Rat')
        stream.writeVInt(1)
        stream.writeVInt(1781092800)
        stream.writeVInt(1781178300)
        stream.writeVInt(1781006400)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Survival - Special Challenge Heavy Rat - 8W3L - Zen Palace - EventChest/Rat')
        stream.writeString('{"Color":"#ae2d13","SurvivalLookup":"328","2v2":false,"lookupValues":[{"id":328,"name":"Survival - Special Challenge Heavy Rat - 8W3L - Zen Palace - EventChest/Rat","lookup":"survival_event_lookup","parameters":{"JoinCost":20,"FreePass":1,"MaxWins":8,"MaxLoss":3,"ManaGeneration":150,"BallDensity":100,"BallScale":100,"NumberOfBalls":1,"NumberOfBallsOnOvertime":2,"ResetWinsOnRetry":false,"NameKey":"survival-specialchallenge-rat-name","DescriptionKey":"survival-rat-desc","Arena":7,"BallType":"1","EndRewardChest":"214","EndRewardSpecificSpell":"326","Deck":["323","22","253","39","43","56","49","35"],"IntermediateRewards":["170","60","189","8","204","189","203"],"GoaliesDisabled":false,"AllowPlayingAfterWin":false,"DisableDeckRandomization":false}},{"id":1,"name":"Ball: Normal","lookup":"ball_lookup","parameters":{"Type":"ball"}},{"id":214,"name":"Reward: Chest - Event Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"39","Amount":0}},{"id":326,"name":"Reward: Spell - Rat (x25)","lookup":"reward_lookup","parameters":{"Type":"SpellSpecific","RefId":"rat","Amount":25}},{"id":323,"name":"Spell: Heavy Rat","lookup":"spell_lookup","parameters":{"RefId":"rat"}},{"id":22,"name":"Spell: Crazy Cat","lookup":"spell_lookup","parameters":{"RefId":"cat"}},{"id":253,"name":"Spell: Spy Chameleon","lookup":"spell_lookup","parameters":{"RefId":"chameleon"}},{"id":39,"name":"Spell: Lover","lookup":"spell_lookup","parameters":{"RefId":"lover"}},{"id":43,"name":"Spell: Melon","lookup":"spell_lookup","parameters":{"RefId":"melon"}},{"id":56,"name":"Spell: Turtle Spinner","lookup":"spell_lookup","parameters":{"RefId":"turtle"}},{"id":49,"name":"Spell: Royal Dung","lookup":"spell_lookup","parameters":{"RefId":"dung"}},{"id":35,"name":"Spell: Ice Boy","lookup":"spell_lookup","parameters":{"RefId":"freeze"}},{"id":170,"name":"Reward: Gold (x40)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":40}},{"id":60,"name":"Reward: Spell - Random Core (x10)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"0","Amount":10}},{"id":189,"name":"Reward: Chest - Silver Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"3","Amount":0}},{"id":8,"name":"Reward: Gold (x200)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":200}},{"id":204,"name":"Reward: Spell - Random Pro (x5)","lookup":"reward_lookup","parameters":{"Type":"SpellByRarity","RefId":"1","Amount":5}},{"id":189,"name":"Reward: Chest - Silver Chest (0% Boost)","lookup":"reward_lookup","parameters":{"Type":"Chest","RefId":"3","Amount":0}},{"id":203,"name":"Reward: Gold (x400)","lookup":"reward_lookup","parameters":{"Type":"Gold","RefId":"-1","Amount":400}}]}')
        stream.writeVInt(0)

        stream.writeBoolean(false)

    }
}