export class LogicSpellDeck {
    static encode(stream) {
        stream.writeBoolean(true)
        stream.writeBoolean(true)
        stream.writeBoolean(true)
        stream.writeBoolean(true)
        stream.writeBoolean(true)
        stream.writeBoolean(true)
        stream.writeBoolean(true)
        stream.writeBoolean(true)

        // LogicSpell
        stream.writeVInt(-1562196636)
        stream.writeVInt(1)
        stream.writeVInt(1)
        stream.writeVInt(1)
        stream.writeVInt(0)
        stream.writeVInt(14)
        stream.writeVInt(14)
        stream.writeVInt(1)
        stream.writeVInt(0)
        stream.writeBoolean(false)
        stream.writeBoolean(false)
        stream.writeVInt(-1)
        stream.writeVInt(-1)
        stream.writeVInt(0)

        // LogicSpell
        stream.writeVInt(349985024)
        stream.writeVInt(0)
        stream.writeVInt(0)
        stream.writeVInt(1)
        stream.writeVInt(1)
        stream.writeVInt(14)
        stream.writeVInt(14)
        stream.writeVInt(0)
        stream.writeVInt(0)
        stream.writeBoolean(false)
        stream.writeBoolean(false)
        stream.writeVInt(-1)
        stream.writeVInt(-1)
        stream.writeVInt(0)

        // LogicSpell
        stream.writeVInt(-1276240925)
        stream.writeVInt(0)
        stream.writeVInt(0)
        stream.writeVInt(1)
        stream.writeVInt(1)
        stream.writeVInt(13)
        stream.writeVInt(13)
        stream.writeVInt(0)
        stream.writeVInt(0)
        stream.writeBoolean(false)
        stream.writeBoolean(false)
        stream.writeVInt(-1)
        stream.writeVInt(-1)
        stream.writeVInt(0)

        // LogicSpell
        stream.writeVInt(-727667870)
        stream.writeVInt(0)
        stream.writeVInt(0)
        stream.writeVInt(1)
        stream.writeVInt(1)
        stream.writeVInt(14)
        stream.writeVInt(14)
        stream.writeVInt(0)
        stream.writeVInt(0)
        stream.writeBoolean(false)
        stream.writeBoolean(false)
        stream.writeVInt(-1)
        stream.writeVInt(-1)
        stream.writeVInt(0)

        // LogicSpell
        stream.writeVInt(-1042652371)
        stream.writeVInt(0)
        stream.writeVInt(0)
        stream.writeVInt(1)
        stream.writeVInt(1)
        stream.writeVInt(13)
        stream.writeVInt(13)
        stream.writeVInt(0)
        stream.writeVInt(0)
        stream.writeBoolean(false)
        stream.writeBoolean(false)
        stream.writeVInt(-1)
        stream.writeVInt(-1)
        stream.writeVInt(0)

        // LogicSpell
        stream.writeVInt(1991136730)
        stream.writeVInt(0)
        stream.writeVInt(0)
        stream.writeVInt(1)
        stream.writeVInt(1)
        stream.writeVInt(13)
        stream.writeVInt(13)
        stream.writeVInt(0)
        stream.writeVInt(0)
        stream.writeBoolean(false)
        stream.writeBoolean(false)
        stream.writeVInt(-1)
        stream.writeVInt(-1)
        stream.writeVInt(0)

        // LogicSpell
        stream.writeVInt(-1656566864)
        stream.writeVInt(0)
        stream.writeVInt(0)
        stream.writeVInt(29787562)
        stream.writeVInt(1)
        stream.writeVInt(12)
        stream.writeVInt(12)
        stream.writeVInt(0)
        stream.writeVInt(0)
        stream.writeBoolean(false)
        stream.writeBoolean(false)
        stream.writeVInt(-1)
        stream.writeVInt(-1)
        stream.writeVInt(0)

        // LogicSpell
        stream.writeVInt(429124811)
        stream.writeVInt(0)
        stream.writeVInt(0)
        stream.writeVInt(29787563)
        stream.writeVInt(1)
        stream.writeVInt(7)
        stream.writeVInt(7)
        stream.writeVInt(0)
        stream.writeVInt(0)
        stream.writeBoolean(false)
        stream.writeBoolean(false)
        stream.writeVInt(-1)
        stream.writeVInt(-1)
        stream.writeVInt(0)
    }

    static encode2(stream) {
        stream.writeBoolean(false)
        stream.writeBoolean(false)
        stream.writeBoolean(false)
        stream.writeBoolean(false)
        stream.writeBoolean(false)
        stream.writeBoolean(false)
        stream.writeBoolean(false)
        stream.writeBoolean(false)
    }
}